import tempfile
import unittest
from pathlib import Path
import os
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtWidgets import QApplication

from ai.course_summarizer import CourseSummaryGenerator
from ai.exam_plan import ExamGenerationPlan
from core.course_initializer import CourseInitializer, build_summary_markdown, infer_topics
from core.document_parser import ExtractedDocument
from models.course_project import CourseProject, CourseProjectManager, CourseTopic
from ui.screens.course_screen import CourseScreen


_APP = QApplication.instance() or QApplication([])


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None
        self.last_error = ""

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder, task=None):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class FakeProfileGenerator:
    profile_source = "llm"
    profile_warning = ""

    def generate(self, title, topics, summary_markdown):
        selected = tuple(topic.title.lower() for topic in topics)
        return ExamGenerationPlan(
            question_count=24,
            difficulty="hard",
            template="final_exam",
            selected_topics=selected,
            topic_weights={topic: 1 for topic in selected},
        )

class CourseSummarySemanticsTests(unittest.TestCase):
    def _docs(self):
            return [
                ExtractedDocument(
                    path="cache.pptx",
                    title="Cache Mapping",
                    extension=".pptx",
                    text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                    pages=["Cache line, byte offset, set, tag."],
                )
            ]

    def _topics(self):
            return [
                CourseTopic(
                    topic_id="cache_mapping",
                    title="Cache Mapping",
                    keywords=["cache line", "tag", "set"],
                    source_files=["cache.pptx"],
                )
            ]

    def test_generate_uses_llm_markdown_when_available(self):
            client = FakeLLMClient("# Semantic Summary\n\n## Cache Mapping\n- Use tag/set/offset.")
            generator = CourseSummaryGenerator(client)

            summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

            self.assertIn("# Semantic Summary", summary)
            self.assertIn("tag/set/offset", summary)
            self.assertIn("Cache line, byte offset", client.messages[1]["content"])
            self.assertEqual("llm", generator.summary_source)
            self.assertEqual("", generator.summary_warning)

    def test_llm_prompt_requires_complete_study_sections(self):
            messages = CourseSummaryGenerator.build_messages(
                "Systems",
                self._docs(),
                self._topics(),
                "# Local Summary",
            )

            prompt = messages[1]["content"]
            for section in ("核心概念", "推演流程", "实际例子", "可考方向", "答题要点"):
                self.assertIn(section, prompt)

    def test_local_summary_contains_complete_study_sections(self):
            summary = build_summary_markdown("Systems", self._docs(), self._topics())

            for section in ("#### 核心概念", "#### 推演流程", "#### 实际例子", "#### 可考方向", "#### 答题要点"):
                self.assertIn(section, summary)

    def test_inferred_topic_keywords_prioritize_topic_terms_over_template_noise(self):
            noisy_cn = "根据课件上下文 关键条件 中间状态 输出结果 整理概念关系 计算步骤 "
            noisy_en = "Core concepts reasoning flow examples exam directions answer points overview "
            text = (
                "# Cache Mapping\n"
                "Cache Mapping splits each byte address into tag, set index, and byte offset. "
                "The cache line tag identifies whether the selected set contains the requested block. "
                + noisy_cn * 30
                + noisy_en * 30
            )
            doc = ExtractedDocument(
                path="cache_mapping.md",
                title="Cache Mapping",
                extension=".md",
                text=text,
                pages=[text],
            )

            topics = infer_topics([doc])

            self.assertEqual("Cache Mapping", topics[0].title)
            self.assertIn("cache", topics[0].keywords)
            self.assertIn("tag", topics[0].keywords)
            self.assertIn("set", topics[0].keywords)
            for noise in ("根据课件", "关键条件", "中间状态", "输出结果", "整理概念", "计算步骤"):
                self.assertNotIn(noise, topics[0].keywords)
            for noise in ("core", "concept", "example", "exam", "answer", "overview"):
                self.assertNotIn(noise, topics[0].keywords)

    def test_inferred_topic_title_skips_generated_summary_scaffold(self):
            scaffold = "根据课件上下文，按输入、关键条件、中间状态和输出结果整理概念关系或计算步骤。"
            text = (
                f"{scaffold}\n"
                "# Cache Mapping\n"
                "Cache Mapping splits byte addresses into tag, set index, and byte offset. "
                "The cache tag is compared after selecting a set. "
            ) * 20
            doc = ExtractedDocument(
                path="slides.md",
                title="slides",
                extension=".md",
                text=text,
                pages=[text],
            )

            topics = infer_topics([doc])

            self.assertEqual("Cache Mapping", topics[0].title)
            self.assertNotIn("根据课件上下文", topics[0].title)

    def test_inferred_topics_ignore_computer_system_auxiliary_material_noise(self):
            cache_text = (
                "Cache mapping explains tag, set index, byte offset, replacement policy, "
                "and set-associative lookup behavior. "
            ) * 12
            noisy_docs = [
                ExtractedDocument(
                    path="standard.md",
                    title="HC Computer System 出题标准",
                    extension=".md",
                    text=("出题对象默认是计算机系统，干扰项更接近真实，批改只讲必要内容。 " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="复习辅助.md",
                    title="复习辅助",
                    extension=".md",
                    text=("课程内容整理标准，模拟卷整理成可复用模板，辅助提示词模板。 " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="课程内容.md",
                    title="课程内容",
                    extension=".md",
                    text=("已生成的课程笔记，核心概念，推演流程，答题要点。 " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="HENGJIA CAO-12组-Superscalar Processor-成绩反馈.pdf",
                    title="HENGJIA CAO-12组-Superscalar Processor-成绩反馈",
                    extension=".pdf",
                    text=("assignment grader feedback simplifications visualization understanding " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="marking-rubric.pdf",
                    title="Marking Rubric",
                    extension=".pdf",
                    text=("marking rubric grading feedback answer key partial credit " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="Tutorial Questions.pdf",
                    title="Tutorial Questions",
                    extension=".pdf",
                    text=("checkpoint question previous discussion answer question bank " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="L15_1_storag… - JupyterLab.pdf",
                    title="L15_1_storag… - JupyterLab",
                    extension=".pdf",
                    text=("select-object fancyarrowpatch privatememorysize pagedattention jupyterlab " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="例题与讲解.md",
                    title="例题与讲解",
                    extension=".md",
                    text=("用途：把高频考点转化为可推理的题。每道例题包含解法和变式提示。 " * 20),
                    pages=[],
                ),
                ExtractedDocument(
                    path="考前40分钟中文摘要.md",
                    title="考前40分钟中文摘要",
                    extension=".md",
                    text=("依据：模拟卷与课程内容的高频核心概念。最后 40 分钟优先级。 " * 20),
                    pages=[],
                ),
            ]
            docs = [
                ExtractedDocument(
                    path="2. Cache mapping.pptx",
                    title="Cache mapping",
                    extension=".pptx",
                    text=cache_text,
                    pages=[cache_text],
                ),
                *noisy_docs,
            ]

            topics = infer_topics(docs)

            titles = [topic.title for topic in topics]
            self.assertIn("Cache Mapping", titles)
            for noisy_title in (
                "HC Computer System 出题标准",
                "复习辅助",
                "课程内容",
                "Marking Rubric",
                "Tutorial Questions",
                "1 Storag Jupyterlab",
                "例题与讲解",
                "考前40分钟中文摘要",
            ):
                self.assertNotIn(noisy_title, titles)
            keywords = {keyword for topic in topics for keyword in topic.keywords}
            for noisy_keyword in (
                "干扰项更接近真实",
                "辅助提示词模板",
                "select-object",
                "fancyarrowpatch",
                "assignmentgrader",
            ):
                self.assertNotIn(noisy_keyword, keywords)

    def test_inferred_topic_title_removes_compound_lecture_number_prefixes(self):
            text = (
                "Virtual memory address translation uses page tables, TLB lookup, page faults, "
                "frames, valid bits, and page replacement policy. "
            ) * 12
            doc = ExtractedDocument(
                path="L15_2_Virtual Memory- Address Translation- and Page Replacement.pdf.pdf",
                title="L15_2_Virtual Memory- Address Translation- and Page Replacement.pdf",
                extension=".pdf",
                text=text,
                pages=[text],
            )

            topics = infer_topics([doc])

            self.assertEqual(
                "Virtual Memory Address Translation And Page Replacement",
                topics[0].title,
            )
            self.assertFalse(topics[0].title.startswith("2 "))

    def test_inferred_topic_title_preserves_year_suffix_but_removes_copy_index(self):
            year_text = (
                "Operating systems coordinate processes, scheduling, memory protection, "
                "system calls, filesystems, interrupts, and device management. "
            ) * 12
            copy_text = (
                "Cache mapping splits byte addresses into tag, set index, byte offset, "
                "cache lines, hits, misses, and replacement policy. "
            ) * 12

            year_topics = infer_topics([
                ExtractedDocument(
                    path="Operating Systems (2024).pdf",
                    title="Operating Systems (2024)",
                    extension=".pdf",
                    text=year_text,
                    pages=[year_text],
                )
            ])
            copy_topics = infer_topics([
                ExtractedDocument(
                    path="Cache Mapping (1).pptx",
                    title="Cache Mapping (1)",
                    extension=".pptx",
                    text=copy_text,
                    pages=[copy_text],
                )
            ])

            self.assertEqual("Operating Systems (2024)", year_topics[0].title)
            self.assertEqual("Cache Mapping", copy_topics[0].title)

    def test_inferred_topic_titles_remove_repository_course_prefixes_and_export_suffixes(self):
            fixtures = [
                (
                    "mit-14-01-microeconomics-summaries",
                    "Microeconomics",
                    "Demand supply price market consumer utility marginal cost elasticity " * 16,
                ),
                (
                    "mit-18-06-linear-algebra-zoomnotes",
                    "Linear Algebra",
                    "Matrix vector column row eigenvalue determinant basis orthogonal linear " * 16,
                ),
                (
                    "mit-7-03-genetics-lecture-1",
                    "Genetics",
                    "Gene DNA mutation chromosome protein allele phenotype genotype inheritance " * 16,
                ),
                (
                    "mit-24-00-ethics-handout",
                    "Ethics",
                    "Moral objectivity obligation reason value action ethical judgment philosophy " * 16,
                ),
                (
                    "cmu-15-213-system-level-io-slides",
                    "System Level Io",
                    "File descriptor read write process stream input output buffer device kernel " * 16,
                ),
            ]
            docs = [
                ExtractedDocument(
                    path=f"{raw_title}.pdf",
                    title=raw_title,
                    extension=".pdf",
                    text=text,
                    pages=[text],
                )
                for raw_title, _expected, text in fixtures
            ]

            topics = infer_topics(docs)

            self.assertEqual(
                {expected for _raw_title, expected, _text in fixtures},
                {topic.title for topic in topics},
            )

    def test_inferred_topic_keywords_drop_general_english_function_words_across_disciplines(self):
            text = (
                "The patient may may may know know our our first first concern, but airway breathing shock trauma "
                "assessment treatment emergency circulation fluid injury. "
            ) * 30
            doc = ExtractedDocument(
                path="basic-emergency-care.pdf",
                title="Basic Emergency Care",
                extension=".pdf",
                text=text,
                pages=[text],
            )

            topics = infer_topics([doc])

            self.assertIn("airway", topics[0].keywords)
            for noise in ("may", "know", "our", "first", "but"):
                self.assertNotIn(noise, topics[0].keywords)

    def test_inferred_topic_keywords_ignore_repeated_pdf_header_lines(self):
            text = "\n".join(
                f"[Page {page}]\n"
                "Example University\nDepartment of Medicine\nCopyright Notice\n"
                f"Case {page} uses airway assessment for breathing circulation shock trauma patient injury."
                for page in range(1, 21)
            )
            doc = ExtractedDocument(
                path="emergency-care.pdf",
                title="Emergency Care",
                extension=".pdf",
                text=text,
                pages=[text],
            )

            topics = infer_topics([doc])

            self.assertIn("airway", topics[0].keywords)
            for noise in ("example", "university", "department", "copyright"):
                self.assertNotIn(noise, topics[0].keywords)

    def test_inferred_topics_ignore_source_manifest_titles(self):
            text = (
                "Source provenance bibliography download URL license author publisher "
                "course material citation reference attribution archive. "
            ) * 20
            doc = ExtractedDocument(
                path="SOURCES.md",
                title="SOURCES",
                extension=".md",
                text=text,
                pages=[text],
            )

            topics = infer_topics([doc])

            self.assertEqual("General Course Review", topics[0].title)

    def test_course_screen_local_agent_initializer_does_not_read_persisted_api_key(self):
            class ForbiddenSecrets:
                def get_key(self):
                    raise AssertionError("local agent course initialization must not read persisted API keys")

            settings = {
                "ai_provider": "local_agent",
                "ai_base_url": "local-agent://auto",
                "ai_model": "codex",
            }

            with tempfile.TemporaryDirectory() as tmpdir, \
                 patch("ui.screens.course_screen.read_json", return_value=settings), \
                 patch("core.secrets_manager.SecretsManager.instance", return_value=ForbiddenSecrets()):
                screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "courses")))
                initializer = screen._build_initializer()

            self.assertIsNotNone(initializer.summary_generator)
            self.assertIsNotNone(initializer.profile_generator)

    def test_generate_falls_back_to_local_summary_when_llm_returns_empty(self):
            client = FakeLLMClient("")
            client.last_error = "API request failed"
            generator = CourseSummaryGenerator(client)

            summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

            self.assertEqual("# Local Summary", summary)
            self.assertEqual("local", generator.summary_source)
            self.assertEqual("API request failed", generator.summary_warning)

    def test_initializer_can_use_injected_summary_generator(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager, summary_generator=FakeSummaryGenerator())
                initializer.parser = FakeParser(self._docs())

                project = initializer.initialize(str(source), title="Systems", make_current=False)

                self.assertIn("# LLM Summary", project.summary_markdown)
                self.assertTrue(Path(project.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))

    def test_initializer_persists_injected_course_generation_profile(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(
                    manager=manager,
                    profile_generator=FakeProfileGenerator(),
                )
                initializer.parser = FakeParser(self._docs())

                project = initializer.initialize(str(source), title="Systems", make_current=False)
                loaded = manager.get(project.course_id)

                self.assertEqual(24, loaded.generation_profile["question_count"])
                self.assertEqual("final_exam", loaded.generation_profile["template"])
                self.assertEqual("llm", loaded.generation_profile_source)
                self.assertEqual("", loaded.generation_profile_warning)

    def test_initializer_can_regenerate_existing_project_summary(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                project = initializer.initialize(str(source), title="Systems", make_current=False)
                original_id = project.course_id
                original_created_at = project.created_at

                initializer.summary_generator = FakeSummaryGenerator()
                initializer.profile_generator = FakeProfileGenerator()
                updated = initializer.regenerate_summary(project, make_current=False)

                self.assertEqual(original_id, updated.course_id)
                self.assertEqual(original_created_at, updated.created_at)
                self.assertIn("# LLM Summary", updated.summary_markdown)
                self.assertGreaterEqual(len(updated.topics), 1)
                self.assertGreaterEqual(len(updated.documents), 1)
                self.assertNotEqual(project.updated_at, updated.updated_at)
                self.assertTrue(Path(updated.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))
                self.assertEqual(24, updated.generation_profile["question_count"])
                self.assertEqual("llm", updated.generation_profile_source)

    def test_regenerate_summary_preserves_topic_id_when_inferred_title_changes(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                old_topic = CourseTopic(
                    topic_id="cache_mapping",
                    title="Cache Mapping",
                    keywords=["cache", "tag", "set"],
                    source_files=[str(source / "cache.pptx")],
                )
                project = CourseProject(
                    course_id="course-topic-stability",
                    title="Systems",
                    source_folder=str(source),
                    summary_markdown="# Old Summary",
                    summary_path="",
                    topics=[old_topic],
                    documents=[],
                    created_at="2026-06-18T00:00:00+00:00",
                    updated_at="2026-06-18T00:00:00+00:00",
                )
                new_text = " ".join(
                    ["cache", "mapping", "tag", "set", "offset", "hit", "miss", "line"] * 14
                )
                initializer.parser = FakeParser([
                    ExtractedDocument(
                        path=str(source / "cache.pptx"),
                        title="Cache Address Mapping",
                        extension=".pptx",
                        text=new_text,
                        pages=[new_text],
                    )
                ])

                updated = initializer.regenerate_summary(project, make_current=False)

                self.assertEqual(1, len(updated.topics))
                self.assertEqual("cache_mapping", updated.topics[0].topic_id)
                self.assertEqual("Cache Address Mapping", updated.topics[0].title)
                self.assertIn("Cache Mapping", updated.topics[0].aliases)
                self.assertIn("cache_address_mapping", updated.topics[0].aliases)
                self.assertIn("cache_mapping", updated.generation_profile["selected_topics"])
                self.assertIn("cache_mapping", updated.generation_profile["topic_weights"])
