import tempfile
import unittest
from pathlib import Path
import os
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtWidgets import QApplication, QMessageBox

from ai.course_summarizer import CourseSummaryGenerator
from core.course_initializer import CourseInitializer
from core.document_parser import ExtractedDocument
from models.course_project import CourseProject, CourseProjectManager, CourseTopic
from ui.screens.course_screen import CourseScreen


_APP = QApplication.instance() or QApplication([])


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class CourseSummaryGeneratorTests(unittest.TestCase):
    def _docs(self):
        return [
            ExtractedDocument(
                path="cache.pptx",
                title="Cache Mapping",
                extension=".pptx",
                text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                pages=["Cache line, byte offset, set, tag."],
            )
        ]

    def _topics(self):
        return [
            CourseTopic(
                topic_id="cache_mapping",
                title="Cache Mapping",
                keywords=["cache line", "tag", "set"],
                source_files=["cache.pptx"],
            )
        ]

    def test_generate_uses_llm_markdown_when_available(self):
        client = FakeLLMClient("# Semantic Summary\n\n## Cache Mapping\n- Use tag/set/offset.")
        generator = CourseSummaryGenerator(client)

        summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

        self.assertIn("# Semantic Summary", summary)
        self.assertIn("tag/set/offset", summary)
        self.assertIn("Cache line, byte offset", client.messages[1]["content"])

    def test_generate_falls_back_to_local_summary_when_llm_returns_empty(self):
        client = FakeLLMClient("")
        generator = CourseSummaryGenerator(client)

        summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

        self.assertEqual("# Local Summary", summary)

    def test_initializer_can_use_injected_summary_generator(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager, summary_generator=FakeSummaryGenerator())
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(str(source), title="Systems", make_current=False)

            self.assertIn("# LLM Summary", project.summary_markdown)
            self.assertTrue(Path(project.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))

    def test_initializer_can_regenerate_existing_project_summary(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())
            project = initializer.initialize(str(source), title="Systems", make_current=False)
            original_id = project.course_id
            original_created_at = project.created_at

            initializer.summary_generator = FakeSummaryGenerator()
            updated = initializer.regenerate_summary(project, make_current=False)

            self.assertEqual(original_id, updated.course_id)
            self.assertEqual(original_created_at, updated.created_at)
            self.assertIn("# LLM Summary", updated.summary_markdown)
            self.assertGreaterEqual(len(updated.topics), 1)
            self.assertGreaterEqual(len(updated.documents), 1)
            self.assertNotEqual(project.updated_at, updated.updated_at)
            self.assertTrue(Path(updated.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))

    def test_project_manager_repairs_stale_summary_path_on_save(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            stale_summary = Path(tmpdir) / "old-cwd" / "quiz_app" / "data" / "courses" / "course-stale_summary.md"
            project = CourseProject(
                course_id="course-stale",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Repaired Summary\n",
                summary_path=str(stale_summary),
                topics=self._topics(),
                documents=[],
                created_at="2026-06-18T00:00:00+00:00",
                updated_at="2026-06-18T00:00:00+00:00",
            )

            self.assertTrue(manager.save(project, make_current=False))

            repaired_summary = Path(manager.directory) / "course-stale_summary.md"
            self.assertEqual(repaired_summary, Path(project.summary_path))
            self.assertEqual("# Repaired Summary\n", repaired_summary.read_text(encoding="utf-8"))
            self.assertFalse(stale_summary.exists())

    def test_course_screen_enables_regenerate_button_for_selected_project(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())
            initializer.initialize(str(source), title="Systems", make_current=False)

            screen = CourseScreen(manager)
            screen.refresh()

            self.assertFalse(screen.regenerate_btn.isEnabled())
            screen.project_list.setCurrentRow(0)
            self.assertTrue(screen.regenerate_btn.isEnabled())

    def test_project_manager_delete_removes_project_summary_and_current_pointer(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            current_file = str(Path(tmpdir) / "current.json")
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())

            with patch("models.course_project.CURRENT_COURSE_FILE", current_file):
                kept = initializer.initialize(str(source), title="Keep", make_current=True)
                deleted = initializer.initialize(str(source), title="Delete", make_current=True)
                deleted_json = Path(manager.directory) / f"{deleted.course_id}.json"
                deleted_summary = Path(deleted.summary_path)

                self.assertTrue(manager.delete(deleted.course_id))

                self.assertFalse(deleted_json.exists())
                self.assertFalse(deleted_summary.exists())
                self.assertEqual(kept.course_id, manager.current().course_id)

    def test_course_screen_can_delete_selected_project(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            current_file = str(Path(tmpdir) / "current.json")
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())

            with patch("models.course_project.CURRENT_COURSE_FILE", current_file):
                project = initializer.initialize(str(source), title="Systems", make_current=True)
                screen = CourseScreen(manager)
                screen.refresh()
                screen.project_list.setCurrentRow(0)

                with patch("ui.screens.course_screen.QMessageBox.question", return_value=QMessageBox.StandardButton.Yes):
                    screen.delete_btn.click()

                self.assertIsNone(manager.get(project.course_id))
                self.assertEqual(0, screen.project_list.count())
                self.assertNotIn("Systems", screen.summary_label.text())


if __name__ == "__main__":
    unittest.main()
