import tempfile
import unittest
from pathlib import Path
import os
from types import SimpleNamespace
from unittest.mock import Mock, patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication, QTextBrowser

from ai.exam_plan import ExamGenerationPlan
from core.course_asset_lifecycle import (
    CourseAssetImpact,
    CourseRemovalMode,
    CourseRemovalResult,
)
from core.course_initializer import CourseInitializer
from core.course_parse_checkpoint import CourseParseCheckpointStore
from core.document_parser import ExtractedDocument
from core.background_task import TaskProgress
from core.language_manager import LanguageManager
from core.topic_identity_migration import TopicIdentityRepairReport, UnmatchedTopicQuestion
from models.course_project import CourseProject, CourseProjectManager, CourseTopic
from ui.screens.course_screen import CourseScreen


_APP = QApplication.instance() or QApplication([])


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None
        self.last_error = ""

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder, task=None):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class FakeProfileGenerator:
    profile_source = "llm"
    profile_warning = ""

    def generate(self, title, topics, summary_markdown):
        selected = tuple(topic.title.lower() for topic in topics)
        return ExamGenerationPlan(
            question_count=24,
            difficulty="hard",
            template="final_exam",
            selected_topics=selected,
            topic_weights={topic: 1 for topic in selected},
        )

class CourseScreenFlowTests(unittest.TestCase):
    def _docs(self):
            return [
                ExtractedDocument(
                    path="cache.pptx",
                    title="Cache Mapping",
                    extension=".pptx",
                    text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                    pages=["Cache line, byte offset, set, tag."],
                )
            ]

    def _topics(self):
            return [
                CourseTopic(
                    topic_id="cache_mapping",
                    title="Cache Mapping",
                    keywords=["cache line", "tag", "set"],
                    source_files=["cache.pptx"],
                )
            ]

    def test_course_screen_surfaces_reusable_parse_checkpoint_without_auto_starting(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                source = root / "materials"
                source.mkdir()
                source_file = source / "lecture.txt"
                source_file.write_text("cache mapping " * 100, encoding="utf-8")
                store = CourseParseCheckpointStore(root / "checkpoints")
                store.save_document(
                    str(source),
                    operation="initialize",
                    course_id="",
                    source_path=source_file,
                    document=ExtractedDocument(
                        str(source_file), "lecture", ".txt", "cached", ["cached"], []
                    ),
                )
                screen = CourseScreen(
                    CourseProjectManager(str(root / "projects")),
                    checkpoint_store=store,
                )

                screen.folder_input.setText(str(source))
                screen._refresh_checkpoint_action()

                self.assertIn("继续", screen.init_btn.text())
                self.assertIn("1", screen.init_btn.toolTip())
                self.assertIs(store, screen.initializer.checkpoint_store)
                self.assertIsNone(screen._init_worker)

    def test_course_screen_progress_and_cancel_controls_follow_worker_state(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)

                screen._set_course_task_active(True)
                screen._on_course_task_progress(TaskProgress(
                    "parsing_file", current=2, total=5, detail="lecture.pdf"
                ))

                self.assertTrue(screen.cancel_task_btn.isVisibleTo(screen))
                self.assertEqual((0, 5), (screen.progress_bar.minimum(), screen.progress_bar.maximum()))
                self.assertEqual(2, screen.progress_bar.value())
                self.assertIn("2 / 5", screen.task_status_label.text())
                self.assertIn("lecture.pdf", screen.task_status_label.text())

                screen._set_course_task_active(False)
                self.assertFalse(screen.cancel_task_btn.isVisibleTo(screen))

    def test_course_screen_shutdown_requests_cancel_without_waiting(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "projects")))
                worker = Mock()
                worker.isRunning.return_value = True
                screen._init_worker = worker

                ready = screen.request_shutdown()

                self.assertFalse(ready)
                worker.cancel.assert_called_once_with()
                worker.wait.assert_not_called()

    def test_course_screen_selects_first_project_and_enables_course_actions(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                initializer.initialize(str(source), title="Systems", make_current=False)

                screen = CourseScreen(manager)
                screen.refresh()

                self.assertEqual(0, screen.project_list.currentRow())
                self.assertTrue(screen.regenerate_action.isEnabled())

    def test_course_screen_does_not_expose_hidden_legacy_generation_button(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "projects")))

        self.assertFalse(hasattr(screen, "generate_questions_btn"))
        self.assertFalse(hasattr(screen, "generate_questions_requested"))

    def test_course_screen_reports_llm_fallback_after_initialization(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-fallback",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Local Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[{"path": "scan.pdf", "warnings": ["OCR unavailable"]}],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                    summary_source="local",
                    summary_warning="API request failed",
                )
                screen = CourseScreen(manager)
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("en")

                with patch("ui.screens.course_screen.QMessageBox.information") as information:
                    screen._on_init_done(project)

                message = information.call_args.args[2]
                self.assertIn("local summary", message.lower())
                self.assertIn("API request failed", message)
                self.assertIn("OCR unavailable", message)

    def test_course_screen_ignores_stale_init_worker_result(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)
                project = CourseProject(
                    course_id="course-stale-init",
                    title="Stale Init",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Stale\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )
                stale_worker = CourseScreen._InitWorker("", "", FakeSummaryGenerator())
                current_worker = CourseScreen._InitWorker("", "", FakeSummaryGenerator())
                screen._init_worker = current_worker
                stale_worker.finished.connect(screen._on_init_done)

                with patch("ui.screens.course_screen.QMessageBox.information") as information:
                    stale_worker.finished.emit(project)

                information.assert_not_called()
                self.assertNotEqual("Stale Init", screen.summary_label.text())

    def test_course_screen_reports_llm_fallback_after_regeneration(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-fallback",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Local Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[{"path": "scan.pdf", "warnings": ["OCR unavailable"]}],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                    summary_source="local",
                    summary_warning="API request failed",
                )
                screen = CourseScreen(manager)
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("en")

                with patch("ui.screens.course_screen.QMessageBox.information") as information:
                    screen._on_regen_done(project)

                message = information.call_args.args[2]
                self.assertIn("local summary", message.lower())
                self.assertIn("API request failed", message)
                self.assertIn("OCR unavailable", message)

    def test_course_screen_ignores_stale_regen_worker_result(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)
                project = CourseProject(
                    course_id="course-stale-regen",
                    title="Stale Regen",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Stale Regen\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )
                stale_worker = CourseScreen._RegenWorker(project, FakeSummaryGenerator())
                current_worker = CourseScreen._RegenWorker(project, FakeSummaryGenerator())
                screen._regen_worker = current_worker
                stale_worker.finished.connect(screen._on_regen_done)

                with patch("ui.screens.course_screen.QMessageBox.information") as information:
                    stale_worker.finished.emit((project, None))

                information.assert_not_called()
                self.assertNotEqual("Stale Regen", screen.summary_label.text())

    def test_course_screen_reports_topic_identity_repair_after_regeneration(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-topic-repair",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )
                report = TopicIdentityRepairReport(
                    scanned=5,
                    updated=2,
                    unmatched=[
                        UnmatchedTopicQuestion("q-unknown", "Unknown Topic", "unmatched")
                    ],
                )
                screen = CourseScreen(manager)
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("zh")

                with patch("ui.screens.course_screen.QMessageBox.information") as information:
                    screen._on_regen_done((project, report))

                message = information.call_args.args[2]
                self.assertIn("已修复 2 道题目的知识点身份", message)
                self.assertIn("1 道题无法自动映射", message)

    def test_course_screen_reports_generation_profile_fallback(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)
                project = CourseProject(
                    course_id="course-profile-fallback",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                    generation_profile_warning="invalid profile JSON",
                )

                message = screen._with_profile_warning("Course ready.", project)

                self.assertIn("invalid profile JSON", message)
                self.assertTrue("本地" in message or "local" in message.lower())

    def test_course_screen_limits_document_warning_details(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("en")
                project = CourseProject(
                    course_id="course-warnings",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[{
                        "path": str(Path(tmpdir) / "scan.pdf"),
                        "warnings": ["warning one", "warning two", "warning three", "warning four"],
                    }],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )

                message = screen._with_document_warnings("Course ready.", project)

                self.assertIn("scan.pdf", message)
                self.assertIn("warning one", message)
                self.assertIn("warning three", message)
                self.assertNotIn("warning four", message)
                self.assertIn("1 more", message)

    def test_course_screen_document_warnings_include_ocr_fix_options(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("en")
                project = CourseProject(
                    course_id="course-ocr-warning",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[{
                        "path": str(Path(tmpdir) / "scan.pdf"),
                        "warnings": ["OCR fallback unavailable: tesseract executable not found"],
                    }],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )

                message = screen._with_document_warnings("Course ready.", project)

                self.assertIn("OCR setup options", message)
                self.assertIn("winget install -e --id UB-Mannheim.TesseractOCR", message)
                self.assertIn("data/tessdata", message)

    def test_course_screen_leaves_message_unchanged_without_document_warnings(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                screen = CourseScreen(manager)
                project = CourseProject(
                    course_id="course-clean",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[{"path": "notes.pdf", "warnings": []}],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )

                self.assertEqual(
                    "Course ready.",
                    screen._with_document_warnings("Course ready.", project),
                )

    def test_course_screen_delete_uses_impact_snapshot_and_selected_policy(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-delete-policy",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-07-13T00:00:00+00:00",
                    updated_at="2026-07-13T00:00:00+00:00",
                )
                self.assertTrue(manager.save(project, make_current=False))
                question_bank = Mock(name="question_bank")
                set_manager = Mock(name="set_manager")
                progress_manager = Mock(name="progress_manager")
                snapshot_manager = Mock(name="snapshot_manager")
                screen = CourseScreen(
                    manager,
                    question_bank=question_bank,
                    set_manager=set_manager,
                    progress_manager=progress_manager,
                    snapshot_manager=snapshot_manager,
                )
                screen.project_list.setCurrentRow(0)
                impact = CourseAssetImpact(
                    course_id=project.course_id,
                    question_ids=("q1", "q2"),
                    direct_set_ids=("set-a",),
                    affected_set_ids=("set-a", "set-b"),
                    progress_ids=("progress-a",),
                    snapshot_ids=("snapshot-a",),
                )
                result = CourseRemovalResult(True, impact)

                with patch(
                    "ui.screens.course_screen.analyze_course_asset_impact",
                    return_value=impact,
                ) as analyze, patch.object(
                    screen,
                    "_choose_course_removal_mode",
                    return_value=CourseRemovalMode.UNLINK_ASSETS,
                ), patch(
                    "ui.screens.course_screen.remove_course_assets",
                    return_value=result,
                ) as remove:
                    screen._delete_selected_project()

                analyze.assert_called_once_with(
                    project.course_id,
                    question_bank,
                    set_manager,
                    progress_manager,
                    snapshot_manager,
                    generation_draft_store=None,
                )
                remove.assert_called_once_with(
                    project.course_id,
                    CourseRemovalMode.UNLINK_ASSETS,
                    course_manager=manager,
                    question_bank=question_bank,
                    set_manager=set_manager,
                    progress_manager=progress_manager,
                    snapshot_manager=snapshot_manager,
                    generation_draft_store=None,
                )

    def test_course_removal_impact_text_explains_counts_and_preserved_history(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "projects")))
                project = SimpleNamespace(title="Systems")
                impact = CourseAssetImpact(
                    course_id="course-a",
                    question_ids=("q1", "q2"),
                    affected_set_ids=("set-a",),
                    progress_ids=("progress-a", "progress-b", "progress-c"),
                    complete_archive_ids=("progress-a",),
                    incomplete_archive_ids=("progress-b",),
                    legacy_archive_ids=("progress-c",),
                    draft_progress_ids=("progress-draft",),
                    snapshot_ids=("snapshot-a",),
                )
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("zh")

                text = screen._course_removal_impact_text(project, impact)

                self.assertIn("相关题目：2", text)
                self.assertIn("相关题集：1", text)
                self.assertIn(
                    "学习记录：3（完整归档 1，残缺归档 1，删除前待迁移 1）",
                    text,
                )
                self.assertIn("未完成草稿：2（删除课程时取消）", text)

    def test_course_removal_mode_text_distinguishes_review_from_retry(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "projects")))
                impact = CourseAssetImpact(
                    course_id="course-a",
                    question_ids=("q1", "q2"),
                    affected_set_ids=("set-a",),
                    progress_ids=("progress-a",),
                    legacy_archive_ids=("progress-a",),
                    draft_progress_ids=("progress-draft",),
                    snapshot_ids=("snapshot-a",),
                )
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("zh")

                keep_text = screen._course_removal_mode_text(
                    CourseRemovalMode.KEEP_ASSETS,
                    impact,
                )
                unlink_text = screen._course_removal_mode_text(
                    CourseRemovalMode.UNLINK_ASSETS,
                    impact,
                )
                delete_text = screen._course_removal_mode_text(
                    CourseRemovalMode.DELETE_LINKED_BANK,
                    impact,
                )

                self.assertIn("题目和题集原样保留", keep_text)
                self.assertIn("移除课程归属和来源定位", unlink_text)
                self.assertIn("历史仍可复盘", delete_text)
                self.assertIn("不能重练", delete_text)
                for text in (keep_text, unlink_text, delete_text):
                    self.assertIn("2 个未完成草稿将取消", text)
                    self.assertIn("删除前先迁移 1 条旧历史", text)

    def test_course_screen_archives_selected_project_without_deleting_identity(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                current_file = str(Path(tmpdir) / "current.json")
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(
                    str(Path(tmpdir) / "projects"),
                    current_course_file=current_file,
                )
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())

                project = initializer.initialize(str(source), title="Systems", make_current=True)
                screen = CourseScreen(manager)
                screen.refresh()
                screen.project_list.setCurrentRow(0)

                screen.archive_action.trigger()

                archived = manager.get(project.course_id)
                self.assertIsNotNone(archived)
                self.assertTrue(archived.is_archived)
                self.assertEqual([], manager.load_all())
                self.assertTrue(screen.archived_scope_btn.isChecked())
                self.assertEqual(1, screen.project_list.count())
                self.assertIn("Systems", screen.project_list.item(0).text())

    def test_course_screen_hides_archive_scope_when_none_exist(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                initializer.initialize(str(source), title="Systems", make_current=True)

                screen = CourseScreen(manager)

                self.assertTrue(screen.active_scope_btn.isHidden())
                self.assertTrue(screen.archived_scope_btn.isHidden())

    def test_course_screen_restores_archived_course_as_current(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                current_file = str(Path(tmpdir) / "current.json")
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(
                    str(Path(tmpdir) / "projects"),
                    current_course_file=current_file,
                )
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                project = initializer.initialize(
                    str(source),
                    title="Systems",
                    make_current=True,
                )
                self.assertTrue(manager.archive(project.course_id))

                screen = CourseScreen(manager)

                self.assertTrue(screen.archived_scope_btn.isChecked())
                self.assertEqual(1, screen.project_list.count())
                self.assertEqual("恢复课程", screen.restore_course_btn.text())
                self.assertTrue(screen.restore_course_btn.isEnabled())

                screen.restore_course_btn.click()

                restored = manager.get(project.course_id)
                self.assertIsNotNone(restored)
                self.assertFalse(restored.is_archived)
                self.assertEqual(project.course_id, manager.current().course_id)
                self.assertTrue(screen.active_scope_btn.isChecked())
                self.assertEqual(
                    project.course_id,
                    screen.project_list.currentItem().data(Qt.ItemDataRole.UserRole),
                )

    def test_archived_course_can_open_its_library_without_restoring(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                project = initializer.initialize(
                    str(source),
                    title="Systems",
                    make_current=True,
                )
                self.assertTrue(manager.archive(project.course_id))
                screen = CourseScreen(manager)
                requested = []
                screen.view_course_library_requested.connect(requested.append)

                screen.view_course_library_btn.click()

                self.assertEqual([project.course_id], requested)
                self.assertTrue(manager.get(project.course_id).is_archived)

    def test_active_course_does_not_duplicate_global_library_entry(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                initializer.initialize(
                    str(source),
                    title="Systems",
                    make_current=True,
                )
                screen = CourseScreen(manager)
                requested = []
                screen.view_course_library_requested.connect(requested.append)

                self.assertTrue(screen.view_course_library_btn.isHidden())
                self.assertFalse(screen.view_course_library_btn.isEnabled())
                self.assertEqual([], requested)

    def test_selecting_active_course_makes_it_current(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                first = CourseProject(
                    course_id="course-first",
                    title="First",
                    source_folder="",
                    summary_markdown="# First",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-29T00:00:00+00:00",
                    updated_at="2026-07-29T00:00:00+00:00",
                )
                second = CourseProject(
                    course_id="course-second",
                    title="Second",
                    source_folder="",
                    summary_markdown="# Second",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-29T00:00:00+00:00",
                    updated_at="2026-07-29T01:00:00+00:00",
                )
                self.assertTrue(manager.save(first, make_current=True))
                self.assertTrue(manager.save(second, make_current=False))
                screen = CourseScreen(manager)
                changed = []
                screen.current_course_changed.connect(lambda: changed.append(True))

                for row in range(screen.project_list.count()):
                    item = screen.project_list.item(row)
                    if item.data(Qt.ItemDataRole.UserRole) == second.course_id:
                        screen.project_list.setCurrentRow(row)
                        break

                self.assertEqual(second.course_id, manager.current().course_id)
                self.assertEqual([True], changed)

    def test_course_screen_uses_archive_as_reversible_default_action(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                initializer.initialize(str(source), title="Systems", make_current=True)

                screen = CourseScreen(manager)

                self.assertEqual("归档课程", screen.archive_action.text())
                self.assertEqual("永久删除…", screen.delete_action.text())

    def test_archiving_current_course_activates_remaining_course(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                current_file = str(Path(tmpdir) / "current.json")
                projects_dir = str(Path(tmpdir) / "projects")
                manager = CourseProjectManager(
                    projects_dir,
                    current_course_file=current_file,
                )
                current = CourseProject(
                    course_id="course-current",
                    title="Current",
                    source_folder="",
                    summary_markdown="# Current",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-29T00:00:00+00:00",
                    updated_at="2026-07-29T00:00:00+00:00",
                )
                remaining = CourseProject(
                    course_id="course-remaining",
                    title="Remaining",
                    source_folder="",
                    summary_markdown="# Remaining",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-29T00:00:00+00:00",
                    updated_at="2026-07-29T01:00:00+00:00",
                )
                self.assertTrue(manager.save(current, make_current=True))
                self.assertTrue(manager.save(remaining, make_current=False))
                screen = CourseScreen(manager)
                for row in range(screen.project_list.count()):
                    item = screen.project_list.item(row)
                    if item.data(Qt.ItemDataRole.UserRole) == current.course_id:
                        screen.project_list.setCurrentRow(row)
                        break

                screen.archive_action.trigger()

                self.assertEqual(remaining.course_id, manager.current().course_id)
                self.assertTrue(screen.active_scope_btn.isChecked())
                self.assertEqual(
                    remaining.course_id,
                    screen.project_list.currentItem().data(Qt.ItemDataRole.UserRole),
                )

    def test_course_screen_guides_user_when_course_library_is_empty(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                language_manager = LanguageManager.instance()
                previous_language = language_manager.current
                self.addCleanup(language_manager.set_language, previous_language)
                language_manager.set_language("zh")

                screen = CourseScreen(manager)

                self.assertEqual(0, screen.project_list.count())
                self.assertFalse(screen.empty_state_label.isHidden())
                self.assertIn("还没有课程", screen.empty_state_label.text())
                self.assertIn("导入", screen.empty_state_label.text())
                self.assertFalse(screen.scope_btn.isEnabled())
                self.assertFalse(screen.delete_action.isEnabled())

    def test_course_screen_can_rename_selected_project(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())
                project = initializer.initialize(str(source), title="Systems", make_current=True)
                screen = CourseScreen(manager)
                screen.refresh()
                screen.project_list.setCurrentRow(0)

                with patch(
                    "ui.screens.course_screen.QInputDialog.getText",
                    return_value=("计算机系统期末", True),
                ):
                    screen.rename_action.trigger()

                renamed = manager.get(project.course_id)
                self.assertEqual("计算机系统期末", renamed.title)
                self.assertIn("计算机系统期末", screen.project_list.item(0).text())
                self.assertIn("计算机系统期末", screen.summary_label.text())

    def test_course_screen_renders_summary_markdown_by_default(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "courses"))
                manager.save(CourseProject(
                    course_id="course-rendered-summary",
                    title="Systems",
                    source_folder="",
                    summary_markdown="# 课程总结\n\n## 核心概念\n\n**DMA** 减少 CPU 搬运。",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-05T00:00:00+00:00",
                    updated_at="2026-07-05T00:00:00+00:00",
                ))

                screen = CourseScreen(manager)

                self.assertIsInstance(screen.summary_preview, QTextBrowser)
                rendered_text = screen.summary_preview.toPlainText()
                self.assertIn("课程总结", rendered_text)
                self.assertIn("核心概念", rendered_text)
                self.assertNotIn("# 课程总结", rendered_text)
                self.assertNotIn("**DMA**", rendered_text)

    def test_course_screen_can_toggle_raw_markdown_summary(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "courses"))
                manager.save(CourseProject(
                    course_id="course-raw-summary",
                    title="Systems",
                    source_folder="",
                    summary_markdown="# 课程总结\n\n**DMA** 减少 CPU 搬运。",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-05T00:00:00+00:00",
                    updated_at="2026-07-05T00:00:00+00:00",
                ))

                screen = CourseScreen(manager)
                screen.summary_mode_btn.click()

                self.assertIn("# 课程总结", screen.summary_preview.toPlainText())
                self.assertIn("**DMA**", screen.summary_preview.toPlainText())
