import tempfile
import unittest
from pathlib import Path
import os
from types import SimpleNamespace
from unittest.mock import Mock, patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtWidgets import QApplication

from ai.course_summarizer import CourseSummaryGenerator
from ai.exam_plan import ExamGenerationPlan
from core.course_initializer import CourseInitializer
from core.document_parser import DocumentParser, ExtractedDocument
from core.background_task import BackgroundTaskCancelled, TaskControl, TaskProgress
from core.background_task_center import BackgroundTaskCenter, TaskStatus
from models.course_project import CourseProject, CourseProjectManager, CourseTopic
from ui.screens.course_screen import CourseScreen


_APP = QApplication.instance() or QApplication([])


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None
        self.last_error = ""

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder, task=None):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class FakeProfileGenerator:
    profile_source = "llm"
    profile_warning = ""

    def generate(self, title, topics, summary_markdown):
        selected = tuple(topic.title.lower() for topic in topics)
        return ExamGenerationPlan(
            question_count=24,
            difficulty="hard",
            template="final_exam",
            selected_topics=selected,
            topic_weights={topic: 1 for topic in selected},
        )

class CourseImportPipelineTests(unittest.TestCase):
    def _docs(self):
            return [
                ExtractedDocument(
                    path="cache.pptx",
                    title="Cache Mapping",
                    extension=".pptx",
                    text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                    pages=["Cache line, byte offset, set, tag."],
                )
            ]

    def _topics(self):
            return [
                CourseTopic(
                    topic_id="cache_mapping",
                    title="Cache Mapping",
                    keywords=["cache line", "tag", "set"],
                    source_files=["cache.pptx"],
                )
            ]

    def test_initializer_persists_an_explicit_file_selection_for_future_rebuilds(self):
            artifacts = SimpleNamespace(
                topics=self._topics(),
                summary_markdown="# Selected files",
                summary_source="local",
                summary_warning="",
                generation_profile={},
                generation_profile_source="local",
                generation_profile_warning="",
            )
            pipeline = Mock()
            pipeline.build.return_value = artifacts

            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                first = root / "week-one" / "memory.md"
                second = root / "week-two" / "io.txt"
                first.parent.mkdir()
                second.parent.mkdir()
                first.write_text("Memory pages and frames.", encoding="utf-8")
                second.write_text("DMA transfers data.", encoding="utf-8")
                manager = CourseProjectManager(str(root / "projects"))
                initializer = CourseInitializer(manager=manager, build_pipeline=pipeline)

                project = initializer.initialize(
                    "",
                    title="Selected Materials",
                    source_files=[str(first), str(second), str(first)],
                    make_current=False,
                )

            self.assertEqual("files", project.source_mode)
            self.assertEqual(
                {str(first.resolve()), str(second.resolve())},
                {document["path"] for document in project.documents},
            )

    def test_regenerate_reuses_the_persisted_explicit_file_selection(self):
            artifacts = SimpleNamespace(
                topics=self._topics(),
                summary_markdown="# Rebuilt selected files",
                summary_source="local",
                summary_warning="",
                generation_profile={},
                generation_profile_source="local",
                generation_profile_warning="",
            )
            pipeline = Mock()
            pipeline.build.return_value = artifacts

            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                first = root / "one" / "memory.md"
                second = root / "two" / "io.txt"
                first.parent.mkdir()
                second.parent.mkdir()
                first.write_text("Memory pages and frames.", encoding="utf-8")
                second.write_text("DMA transfers data.", encoding="utf-8")
                manager = CourseProjectManager(str(root / "projects"))
                initializer = CourseInitializer(manager=manager, build_pipeline=pipeline)
                project = initializer.initialize(
                    "",
                    title="Selected Materials",
                    source_files=[str(first), str(second)],
                    make_current=False,
                )
                pipeline.reset_mock()

                updated = initializer.regenerate_summary(project, make_current=False)

            pipeline.build.assert_called_once()
            rebuilt_docs = pipeline.build.call_args.args[1]
            self.assertEqual({"memory", "io"}, {document.title for document in rebuilt_docs})
            self.assertEqual("files", updated.source_mode)

    def test_course_screen_stages_unique_supported_files_before_starting_import(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                first = root / "lecture-one.md"
                second = root / "lecture-two.pdf"
                first.write_text("Memory pages and frames.", encoding="utf-8")
                second.write_bytes(b"%PDF-1.4")
                screen = CourseScreen(CourseProjectManager(str(root / "projects")))
                self.addCleanup(screen.close)

                screen._stage_files([str(first), str(second), str(first)])

                self.assertEqual(2, screen.staged_files_list.count())
                self.assertEqual(str(first), screen.staged_files_list.item(0).data(0x0100))
                self.assertEqual(str(second), screen.staged_files_list.item(1).data(0x0100))
                self.assertTrue(screen.init_btn.isEnabled())

                screen._clear_staged_files()

                self.assertEqual(0, screen.staged_files_list.count())

    def test_course_init_worker_forwards_staged_files_to_initializer(self):
            captured = {}

            class CapturingInitializer:
                def initialize(self, folder, title, *, task=None, source_files=None):
                    captured.update(
                        folder=folder,
                        title=title,
                        source_files=source_files,
                    )
                    return SimpleNamespace(title=title, documents=[], topics=[])

            worker = CourseScreen._InitWorker(
                "",
                "Selected Materials",
                CapturingInitializer(),
                source_files=["one.md", "two.pdf"],
            )
            worker.run()

            self.assertEqual("", captured["folder"])
            self.assertEqual("Selected Materials", captured["title"])
            self.assertEqual(["one.md", "two.pdf"], captured["source_files"])

    def test_llm_summary_prompt_does_not_expose_absolute_source_paths(self):
            private_path = r"C:\Users\student\Downloads\private-course\lecture.md"
            messages = CourseSummaryGenerator.build_messages(
                "Course",
                [
                    ExtractedDocument(
                        path=private_path,
                        title="lecture",
                        extension=".md",
                        text="Course content",
                    )
                ],
                [],
                "# Local summary",
            )

            prompt = messages[-1]["content"]
            self.assertIn("Source: lecture (.md)", prompt)
            self.assertNotIn(private_path, prompt)
            self.assertNotIn(r"C:\Users\student", prompt)

    def test_initialize_delegates_semantic_artifact_building_to_pipeline(self):
            topics = self._topics()
            artifacts = SimpleNamespace(
                topics=topics,
                summary_markdown="# Pipeline Summary",
                summary_source="pipeline",
                summary_warning="",
                generation_profile={"question_count": 12},
                generation_profile_source="pipeline",
                generation_profile_warning="",
            )
            pipeline = Mock()
            pipeline.build.return_value = artifacts

            with tempfile.TemporaryDirectory() as tmpdir:
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                initializer = CourseInitializer(manager=manager, build_pipeline=pipeline)
                initializer.parser = FakeParser(self._docs())

                project = initializer.initialize(str(source), title="Systems", make_current=False)

            pipeline.build.assert_called_once_with(
                "Systems",
                self._docs(),
                previous_topics=None,
                task=None,
            )
            self.assertEqual("# Pipeline Summary", project.summary_markdown)
            self.assertEqual("pipeline", project.summary_source)
            self.assertEqual({"question_count": 12}, project.generation_profile)

    def test_regenerate_delegates_semantic_artifact_building_to_same_pipeline(self):
            previous_topics = self._topics()
            artifacts = SimpleNamespace(
                topics=previous_topics,
                summary_markdown="# Regenerated by Pipeline",
                summary_source="pipeline",
                summary_warning="",
                generation_profile={"question_count": 18},
                generation_profile_source="pipeline",
                generation_profile_warning="",
            )
            pipeline = Mock()
            pipeline.build.return_value = artifacts

            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-pipeline",
                    title="Systems",
                    source_folder=tmpdir,
                    summary_markdown="# Original",
                    summary_path="",
                    topics=previous_topics,
                    documents=[],
                    created_at="2026-07-01T00:00:00+00:00",
                    updated_at="2026-07-01T00:00:00+00:00",
                )
                initializer = CourseInitializer(manager=manager, build_pipeline=pipeline)
                initializer.parser = FakeParser(self._docs())

                updated = initializer.regenerate_summary(project, make_current=False)

            pipeline.build.assert_called_once_with(
                "Systems",
                self._docs(),
                previous_topics=previous_topics,
                task=None,
            )
            self.assertEqual("# Regenerated by Pipeline", updated.summary_markdown)
            self.assertEqual({"question_count": 18}, updated.generation_profile)

    def test_initialize_rejects_folders_with_only_unreadable_documents(self):
            manager = Mock()
            initializer = CourseInitializer(manager=manager)
            with tempfile.TemporaryDirectory() as tmpdir:
                Path(tmpdir, "failed-download.pdf").write_text(
                    "not a real PDF container",
                    encoding="utf-8",
                )

                with self.assertRaisesRegex(ValueError, "No readable course content"):
                    initializer.initialize(tmpdir, title="Broken import")

            manager.save.assert_not_called()

    def test_initializer_reports_save_failure_instead_of_returning_unsaved_course(self):
            manager = Mock()
            manager.save.return_value = False
            initializer = CourseInitializer(manager)
            initializer.parser = FakeParser(self._docs())

            with self.assertRaisesRegex(OSError, "save course data"):
                initializer.initialize("unused-source", make_current=False)

    def test_initializer_cancelled_after_parsing_does_not_save_partial_project(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                task = TaskControl()

                class CancellingParser:
                    def parse_folder(self, folder, task=None):
                        task.cancel()
                        return self_docs

                self_docs = self._docs()
                initializer = CourseInitializer(manager)
                initializer.parser = CancellingParser()

                with self.assertRaises(BackgroundTaskCancelled):
                    initializer.initialize(tmpdir, task=task)

                self.assertEqual([], manager.load_all())

    def test_initializer_reports_structured_stages_before_saving(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                events = []
                task = TaskControl(events.append)
                initializer = CourseInitializer(manager)
                initializer.parser = FakeParser(self._docs())

                project = initializer.initialize(tmpdir, task=task)

                self.assertEqual(project.course_id, manager.current().course_id)
                stages = [event.stage for event in events]
                self.assertIn("topics", stages)
                self.assertIn("summary", stages)
                self.assertIn("profile", stages)
                self.assertIn("index", stages)
                self.assertEqual("saved", stages[-1])

    def test_regeneration_cancel_does_not_overwrite_existing_project(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-stable",
                    title="Systems",
                    source_folder=tmpdir,
                    summary_markdown="# Original Summary",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-07-01T00:00:00+00:00",
                    updated_at="2026-07-01T00:00:00+00:00",
                )
                manager.save(project)
                task = TaskControl()

                class CancellingParser:
                    def parse_folder(self, folder, task=None):
                        task.cancel()
                        return self_docs

                self_docs = self._docs()
                initializer = CourseInitializer(manager)
                initializer.parser = CancellingParser()

                with self.assertRaises(BackgroundTaskCancelled):
                    initializer.regenerate_summary(project, task=task)

                stored = manager.get(project.course_id)
                self.assertEqual("# Original Summary", stored.summary_markdown)
                self.assertEqual("2026-07-01T00:00:00+00:00", stored.updated_at)

    def test_document_parser_cancels_between_files_and_reports_filename(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                (root / "first.txt").write_text("cache mapping " * 100, encoding="utf-8")
                (root / "second.txt").write_text("process scheduling " * 100, encoding="utf-8")
                events = []
                task = TaskControl()

                def on_progress(event):
                    events.append(event)
                    if event.stage == "parsing_file" and event.current == 1:
                        task.cancel()

                task = TaskControl(on_progress)

                with self.assertRaises(BackgroundTaskCancelled):
                    DocumentParser().parse_folder(tmpdir, task=task)

                parsed = [event for event in events if event.stage == "parsing_file"]
                self.assertEqual(1, len(parsed))
                self.assertEqual("first.txt", parsed[0].detail)
                self.assertEqual(2, parsed[0].total)

    def test_course_init_worker_emits_cancelled_instead_of_error(self):
            class BlockingInitializer:
                def initialize(self, folder, title, task=None):
                    task.check_cancelled()

            worker = CourseScreen._InitWorker("folder", "title", BlockingInitializer())
            cancelled = []
            errors = []
            worker.cancelled.connect(lambda: cancelled.append(True))
            worker.error.connect(errors.append)

            worker.cancel()
            worker.run()

            self.assertEqual([True], cancelled)
            self.assertEqual([], errors)

    def test_course_import_persists_runtime_progress_and_completion(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                source = root / "source"
                source.mkdir()
                manager = CourseProjectManager(str(root / "projects"))
                task_center = BackgroundTaskCenter()
                screen = CourseScreen(manager, task_center=task_center)
                screen.folder_input.setText(str(source))
                screen.title_input.setText("Systems")

                with patch.object(screen, "_build_initializer", return_value=Mock()), \
                     patch.object(CourseScreen._InitWorker, "start"):
                    screen._initialize_course()

                snapshot = task_center.snapshots()[0]
                self.assertEqual("course_import", snapshot.kind)
                self.assertEqual(TaskStatus.RUNNING, snapshot.status)
                self.assertEqual(str(source), snapshot.metadata["source_folder"])

                screen._on_course_task_progress(
                    TaskProgress("parsing_file", current=2, total=5, detail="io.pdf")
                )
                self.assertEqual(
                    "parsing_file", task_center.get(snapshot.task_id).progress.stage
                )

                project = SimpleNamespace(
                    title="Systems",
                    documents=[{"path": "io.pdf", "warnings": []}],
                    topics=[SimpleNamespace(topic_id="io")],
                    summary_warning="",
                    generation_profile_warning="",
                )
                with patch("ui.screens.course_screen.QMessageBox.information"):
                    screen._on_init_done(project)

                completed = task_center.get(snapshot.task_id)
                self.assertEqual(TaskStatus.COMPLETED, completed.status)
                self.assertEqual(1, completed.result_count)

    def test_course_task_cancel_uses_persistent_cancel_callback(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                source = root / "source"
                source.mkdir()
                task_center = BackgroundTaskCenter()
                screen = CourseScreen(
                    CourseProjectManager(str(root / "projects")),
                    task_center=task_center,
                )
                screen.folder_input.setText(str(source))

                with patch.object(screen, "_build_initializer", return_value=Mock()), \
                     patch.object(CourseScreen._InitWorker, "start"), \
                     patch.object(CourseScreen._InitWorker, "cancel") as cancel:
                    screen._initialize_course()
                    screen._cancel_course_task()

                    cancel.assert_called_once_with()
                    self.assertEqual(
                        TaskStatus.CANCELLING,
                        task_center.snapshots()[0].status,
                    )
