import json
import tempfile
import unittest
from pathlib import Path
import os
from types import SimpleNamespace
from unittest.mock import Mock, patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtWidgets import QApplication, QTextBrowser

from ai.course_summarizer import CourseSummaryGenerator
from ai.exam_plan import ExamGenerationPlan
from core.course_asset_lifecycle import (
    CourseAssetImpact,
    CourseRemovalMode,
    CourseRemovalResult,
)
from core.course_initializer import CourseInitializer, build_summary_markdown, infer_topics
from core.course_parse_checkpoint import CourseParseCheckpointStore
from core.document_parser import DocumentParser, ExtractedDocument
from core.background_task import BackgroundTaskCancelled, TaskControl, TaskProgress
from core.background_task_center import BackgroundTaskCenter, TaskStatus
from core.language_manager import LanguageManager
from core.topic_identity_migration import TopicIdentityRepairReport, UnmatchedTopicQuestion
from models.course_project import CourseProject, CourseProjectManager, CourseTopic
from ui.screens.course_screen import CourseScreen


_APP = QApplication.instance() or QApplication([])


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None
        self.last_error = ""

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder, task=None):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class FakeProfileGenerator:
    profile_source = "llm"
    profile_warning = ""

    def generate(self, title, topics, summary_markdown):
        selected = tuple(topic.title.lower() for topic in topics)
        return ExamGenerationPlan(
            question_count=24,
            difficulty="hard",
            template="final_exam",
            selected_topics=selected,
            topic_weights={topic: 1 for topic in selected},
        )


class CourseSummaryGeneratorTests(unittest.TestCase):
    def test_llm_summary_prompt_does_not_expose_absolute_source_paths(self):
        private_path = r"C:\Users\student\Downloads\private-course\lecture.md"
        messages = CourseSummaryGenerator.build_messages(
            "Course",
            [
                ExtractedDocument(
                    path=private_path,
                    title="lecture",
                    extension=".md",
                    text="Course content",
                )
            ],
            [],
            "# Local summary",
        )

        prompt = messages[-1]["content"]
        self.assertIn("Source: lecture (.md)", prompt)
        self.assertNotIn(private_path, prompt)
        self.assertNotIn(r"C:\Users\student", prompt)

    def test_initialize_delegates_semantic_artifact_building_to_pipeline(self):
        topics = self._topics()
        artifacts = SimpleNamespace(
            topics=topics,
            summary_markdown="# Pipeline Summary",
            summary_source="pipeline",
            summary_warning="",
            generation_profile={"question_count": 12},
            generation_profile_source="pipeline",
            generation_profile_warning="",
        )
        pipeline = Mock()
        pipeline.build.return_value = artifacts

        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager, build_pipeline=pipeline)
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(str(source), title="Systems", make_current=False)

        pipeline.build.assert_called_once_with(
            "Systems",
            self._docs(),
            previous_topics=None,
            task=None,
        )
        self.assertEqual("# Pipeline Summary", project.summary_markdown)
        self.assertEqual("pipeline", project.summary_source)
        self.assertEqual({"question_count": 12}, project.generation_profile)

    def test_regenerate_delegates_semantic_artifact_building_to_same_pipeline(self):
        previous_topics = self._topics()
        artifacts = SimpleNamespace(
            topics=previous_topics,
            summary_markdown="# Regenerated by Pipeline",
            summary_source="pipeline",
            summary_warning="",
            generation_profile={"question_count": 18},
            generation_profile_source="pipeline",
            generation_profile_warning="",
        )
        pipeline = Mock()
        pipeline.build.return_value = artifacts

        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-pipeline",
                title="Systems",
                source_folder=tmpdir,
                summary_markdown="# Original",
                summary_path="",
                topics=previous_topics,
                documents=[],
                created_at="2026-07-01T00:00:00+00:00",
                updated_at="2026-07-01T00:00:00+00:00",
            )
            initializer = CourseInitializer(manager=manager, build_pipeline=pipeline)
            initializer.parser = FakeParser(self._docs())

            updated = initializer.regenerate_summary(project, make_current=False)

        pipeline.build.assert_called_once_with(
            "Systems",
            self._docs(),
            previous_topics=previous_topics,
            task=None,
        )
        self.assertEqual("# Regenerated by Pipeline", updated.summary_markdown)
        self.assertEqual({"question_count": 18}, updated.generation_profile)

    def test_course_screen_surfaces_reusable_parse_checkpoint_without_auto_starting(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            source = root / "materials"
            source.mkdir()
            source_file = source / "lecture.txt"
            source_file.write_text("cache mapping " * 100, encoding="utf-8")
            store = CourseParseCheckpointStore(root / "checkpoints")
            store.save_document(
                str(source),
                operation="initialize",
                course_id="",
                source_path=source_file,
                document=ExtractedDocument(
                    str(source_file), "lecture", ".txt", "cached", ["cached"], []
                ),
            )
            screen = CourseScreen(
                CourseProjectManager(str(root / "projects")),
                checkpoint_store=store,
            )

            screen.folder_input.setText(str(source))
            screen._refresh_checkpoint_action()

            self.assertIn("继续", screen.init_btn.text())
            self.assertIn("1", screen.init_btn.toolTip())
            self.assertIs(store, screen.initializer.checkpoint_store)
            self.assertIsNone(screen._init_worker)

    def test_initialize_rejects_folders_with_only_unreadable_documents(self):
        manager = Mock()
        initializer = CourseInitializer(manager=manager)
        with tempfile.TemporaryDirectory() as tmpdir:
            Path(tmpdir, "failed-download.pdf").write_text(
                "not a real PDF container",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, "No readable course content"):
                initializer.initialize(tmpdir, title="Broken import")

        manager.save.assert_not_called()

    def test_initializer_reports_save_failure_instead_of_returning_unsaved_course(self):
        manager = Mock()
        manager.save.return_value = False
        initializer = CourseInitializer(manager)
        initializer.parser = FakeParser(self._docs())

        with self.assertRaisesRegex(OSError, "save course data"):
            initializer.initialize("unused-source", make_current=False)

    def test_initializer_cancelled_after_parsing_does_not_save_partial_project(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            task = TaskControl()

            class CancellingParser:
                def parse_folder(self, folder, task=None):
                    task.cancel()
                    return self_docs

            self_docs = self._docs()
            initializer = CourseInitializer(manager)
            initializer.parser = CancellingParser()

            with self.assertRaises(BackgroundTaskCancelled):
                initializer.initialize(tmpdir, task=task)

            self.assertEqual([], manager.load_all())

    def test_initializer_reports_structured_stages_before_saving(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            events = []
            task = TaskControl(events.append)
            initializer = CourseInitializer(manager)
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(tmpdir, task=task)

            self.assertEqual(project.course_id, manager.current().course_id)
            stages = [event.stage for event in events]
            self.assertIn("topics", stages)
            self.assertIn("summary", stages)
            self.assertIn("profile", stages)
            self.assertIn("index", stages)
            self.assertEqual("saved", stages[-1])

    def test_regeneration_cancel_does_not_overwrite_existing_project(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-stable",
                title="Systems",
                source_folder=tmpdir,
                summary_markdown="# Original Summary",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-07-01T00:00:00+00:00",
                updated_at="2026-07-01T00:00:00+00:00",
            )
            manager.save(project)
            task = TaskControl()

            class CancellingParser:
                def parse_folder(self, folder, task=None):
                    task.cancel()
                    return self_docs

            self_docs = self._docs()
            initializer = CourseInitializer(manager)
            initializer.parser = CancellingParser()

            with self.assertRaises(BackgroundTaskCancelled):
                initializer.regenerate_summary(project, task=task)

            stored = manager.get(project.course_id)
            self.assertEqual("# Original Summary", stored.summary_markdown)
            self.assertEqual("2026-07-01T00:00:00+00:00", stored.updated_at)

    def test_document_parser_cancels_between_files_and_reports_filename(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            (root / "first.txt").write_text("cache mapping " * 100, encoding="utf-8")
            (root / "second.txt").write_text("process scheduling " * 100, encoding="utf-8")
            events = []
            task = TaskControl()

            def on_progress(event):
                events.append(event)
                if event.stage == "parsing_file" and event.current == 1:
                    task.cancel()

            task = TaskControl(on_progress)

            with self.assertRaises(BackgroundTaskCancelled):
                DocumentParser().parse_folder(tmpdir, task=task)

            parsed = [event for event in events if event.stage == "parsing_file"]
            self.assertEqual(1, len(parsed))
            self.assertEqual("first.txt", parsed[0].detail)
            self.assertEqual(2, parsed[0].total)

    def test_course_init_worker_emits_cancelled_instead_of_error(self):
        class BlockingInitializer:
            def initialize(self, folder, title, task=None):
                task.check_cancelled()

        worker = CourseScreen._InitWorker("folder", "title", BlockingInitializer())
        cancelled = []
        errors = []
        worker.cancelled.connect(lambda: cancelled.append(True))
        worker.error.connect(errors.append)

        worker.cancel()
        worker.run()

        self.assertEqual([True], cancelled)
        self.assertEqual([], errors)

    def test_course_screen_progress_and_cancel_controls_follow_worker_state(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)

            screen._set_course_task_active(True)
            screen._on_course_task_progress(TaskProgress(
                "parsing_file", current=2, total=5, detail="lecture.pdf"
            ))

            self.assertTrue(screen.cancel_task_btn.isVisibleTo(screen))
            self.assertEqual((0, 5), (screen.progress_bar.minimum(), screen.progress_bar.maximum()))
            self.assertEqual(2, screen.progress_bar.value())
            self.assertIn("2 / 5", screen.task_status_label.text())
            self.assertIn("lecture.pdf", screen.task_status_label.text())

            screen._set_course_task_active(False)
            self.assertFalse(screen.cancel_task_btn.isVisibleTo(screen))

    def test_course_screen_shutdown_requests_cancel_without_waiting(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "projects")))
            worker = Mock()
            worker.isRunning.return_value = True
            screen._init_worker = worker

            ready = screen.request_shutdown()

            self.assertFalse(ready)
            worker.cancel.assert_called_once_with()
            worker.wait.assert_not_called()

    def test_course_import_persists_runtime_progress_and_completion(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            source = root / "source"
            source.mkdir()
            manager = CourseProjectManager(str(root / "projects"))
            task_center = BackgroundTaskCenter(root / "tasks.json")
            screen = CourseScreen(manager, task_center=task_center)
            screen.folder_input.setText(str(source))
            screen.title_input.setText("Systems")

            with patch.object(screen, "_build_initializer", return_value=Mock()), \
                 patch.object(CourseScreen._InitWorker, "start"):
                screen._initialize_course()

            snapshot = task_center.snapshots()[0]
            self.assertEqual("course_import", snapshot.kind)
            self.assertEqual(TaskStatus.RUNNING, snapshot.status)
            self.assertEqual(str(source), snapshot.metadata["source_folder"])

            screen._on_course_task_progress(
                TaskProgress("parsing_file", current=2, total=5, detail="io.pdf")
            )
            self.assertEqual(
                "parsing_file", task_center.get(snapshot.task_id).progress.stage
            )

            project = SimpleNamespace(
                title="Systems",
                documents=[{"path": "io.pdf", "warnings": []}],
                topics=[SimpleNamespace(topic_id="io")],
                summary_warning="",
                generation_profile_warning="",
            )
            with patch("ui.screens.course_screen.QMessageBox.information"):
                screen._on_init_done(project)

            completed = task_center.get(snapshot.task_id)
            self.assertEqual(TaskStatus.COMPLETED, completed.status)
            self.assertEqual(1, completed.result_count)

    def test_course_task_cancel_uses_persistent_cancel_callback(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            source = root / "source"
            source.mkdir()
            task_center = BackgroundTaskCenter(root / "tasks.json")
            screen = CourseScreen(
                CourseProjectManager(str(root / "projects")),
                task_center=task_center,
            )
            screen.folder_input.setText(str(source))

            with patch.object(screen, "_build_initializer", return_value=Mock()), \
                 patch.object(CourseScreen._InitWorker, "start"), \
                 patch.object(CourseScreen._InitWorker, "cancel") as cancel:
                screen._initialize_course()
                screen._cancel_course_task()

                cancel.assert_called_once_with()
                self.assertEqual(
                    TaskStatus.CANCELLING,
                    task_center.snapshots()[0].status,
                )
    def _docs(self):
        return [
            ExtractedDocument(
                path="cache.pptx",
                title="Cache Mapping",
                extension=".pptx",
                text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                pages=["Cache line, byte offset, set, tag."],
            )
        ]

    def _topics(self):
        return [
            CourseTopic(
                topic_id="cache_mapping",
                title="Cache Mapping",
                keywords=["cache line", "tag", "set"],
                source_files=["cache.pptx"],
            )
        ]

    def test_generate_uses_llm_markdown_when_available(self):
        client = FakeLLMClient("# Semantic Summary\n\n## Cache Mapping\n- Use tag/set/offset.")
        generator = CourseSummaryGenerator(client)

        summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

        self.assertIn("# Semantic Summary", summary)
        self.assertIn("tag/set/offset", summary)
        self.assertIn("Cache line, byte offset", client.messages[1]["content"])
        self.assertEqual("llm", generator.summary_source)
        self.assertEqual("", generator.summary_warning)

    def test_llm_prompt_requires_complete_study_sections(self):
        messages = CourseSummaryGenerator.build_messages(
            "Systems",
            self._docs(),
            self._topics(),
            "# Local Summary",
        )

        prompt = messages[1]["content"]
        for section in ("核心概念", "推演流程", "实际例子", "可考方向", "答题要点"):
            self.assertIn(section, prompt)

    def test_local_summary_contains_complete_study_sections(self):
        summary = build_summary_markdown("Systems", self._docs(), self._topics())

        for section in ("#### 核心概念", "#### 推演流程", "#### 实际例子", "#### 可考方向", "#### 答题要点"):
            self.assertIn(section, summary)

    def test_inferred_topic_keywords_prioritize_topic_terms_over_template_noise(self):
        noisy_cn = "根据课件上下文 关键条件 中间状态 输出结果 整理概念关系 计算步骤 "
        noisy_en = "Core concepts reasoning flow examples exam directions answer points overview "
        text = (
            "# Cache Mapping\n"
            "Cache Mapping splits each byte address into tag, set index, and byte offset. "
            "The cache line tag identifies whether the selected set contains the requested block. "
            + noisy_cn * 30
            + noisy_en * 30
        )
        doc = ExtractedDocument(
            path="cache_mapping.md",
            title="Cache Mapping",
            extension=".md",
            text=text,
            pages=[text],
        )

        topics = infer_topics([doc])

        self.assertEqual("Cache Mapping", topics[0].title)
        self.assertIn("cache", topics[0].keywords)
        self.assertIn("tag", topics[0].keywords)
        self.assertIn("set", topics[0].keywords)
        for noise in ("根据课件", "关键条件", "中间状态", "输出结果", "整理概念", "计算步骤"):
            self.assertNotIn(noise, topics[0].keywords)
        for noise in ("core", "concept", "example", "exam", "answer", "overview"):
            self.assertNotIn(noise, topics[0].keywords)

    def test_inferred_topic_title_skips_generated_summary_scaffold(self):
        scaffold = "根据课件上下文，按输入、关键条件、中间状态和输出结果整理概念关系或计算步骤。"
        text = (
            f"{scaffold}\n"
            "# Cache Mapping\n"
            "Cache Mapping splits byte addresses into tag, set index, and byte offset. "
            "The cache tag is compared after selecting a set. "
        ) * 20
        doc = ExtractedDocument(
            path="slides.md",
            title="slides",
            extension=".md",
            text=text,
            pages=[text],
        )

        topics = infer_topics([doc])

        self.assertEqual("Cache Mapping", topics[0].title)
        self.assertNotIn("根据课件上下文", topics[0].title)

    def test_inferred_topics_ignore_computer_system_auxiliary_material_noise(self):
        cache_text = (
            "Cache mapping explains tag, set index, byte offset, replacement policy, "
            "and set-associative lookup behavior. "
        ) * 12
        noisy_docs = [
            ExtractedDocument(
                path="standard.md",
                title="HC Computer System 出题标准",
                extension=".md",
                text=("出题对象默认是计算机系统，干扰项更接近真实，批改只讲必要内容。 " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="复习辅助.md",
                title="复习辅助",
                extension=".md",
                text=("课程内容整理标准，模拟卷整理成可复用模板，辅助提示词模板。 " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="课程内容.md",
                title="课程内容",
                extension=".md",
                text=("已生成的课程笔记，核心概念，推演流程，答题要点。 " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="HENGJIA CAO-12组-Superscalar Processor-成绩反馈.pdf",
                title="HENGJIA CAO-12组-Superscalar Processor-成绩反馈",
                extension=".pdf",
                text=("assignment grader feedback simplifications visualization understanding " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="marking-rubric.pdf",
                title="Marking Rubric",
                extension=".pdf",
                text=("marking rubric grading feedback answer key partial credit " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="Tutorial Questions.pdf",
                title="Tutorial Questions",
                extension=".pdf",
                text=("checkpoint question previous discussion answer question bank " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="L15_1_storag… - JupyterLab.pdf",
                title="L15_1_storag… - JupyterLab",
                extension=".pdf",
                text=("select-object fancyarrowpatch privatememorysize pagedattention jupyterlab " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="例题与讲解.md",
                title="例题与讲解",
                extension=".md",
                text=("用途：把高频考点转化为可推理的题。每道例题包含解法和变式提示。 " * 20),
                pages=[],
            ),
            ExtractedDocument(
                path="考前40分钟中文摘要.md",
                title="考前40分钟中文摘要",
                extension=".md",
                text=("依据：模拟卷与课程内容的高频核心概念。最后 40 分钟优先级。 " * 20),
                pages=[],
            ),
        ]
        docs = [
            ExtractedDocument(
                path="2. Cache mapping.pptx",
                title="Cache mapping",
                extension=".pptx",
                text=cache_text,
                pages=[cache_text],
            ),
            *noisy_docs,
        ]

        topics = infer_topics(docs)

        titles = [topic.title for topic in topics]
        self.assertIn("Cache Mapping", titles)
        for noisy_title in (
            "HC Computer System 出题标准",
            "复习辅助",
            "课程内容",
            "Marking Rubric",
            "Tutorial Questions",
            "1 Storag Jupyterlab",
            "例题与讲解",
            "考前40分钟中文摘要",
        ):
            self.assertNotIn(noisy_title, titles)
        keywords = {keyword for topic in topics for keyword in topic.keywords}
        for noisy_keyword in (
            "干扰项更接近真实",
            "辅助提示词模板",
            "select-object",
            "fancyarrowpatch",
            "assignmentgrader",
        ):
            self.assertNotIn(noisy_keyword, keywords)

    def test_inferred_topic_title_removes_compound_lecture_number_prefixes(self):
        text = (
            "Virtual memory address translation uses page tables, TLB lookup, page faults, "
            "frames, valid bits, and page replacement policy. "
        ) * 12
        doc = ExtractedDocument(
            path="L15_2_Virtual Memory- Address Translation- and Page Replacement.pdf.pdf",
            title="L15_2_Virtual Memory- Address Translation- and Page Replacement.pdf",
            extension=".pdf",
            text=text,
            pages=[text],
        )

        topics = infer_topics([doc])

        self.assertEqual(
            "Virtual Memory Address Translation And Page Replacement",
            topics[0].title,
        )
        self.assertFalse(topics[0].title.startswith("2 "))

    def test_inferred_topic_title_preserves_year_suffix_but_removes_copy_index(self):
        year_text = (
            "Operating systems coordinate processes, scheduling, memory protection, "
            "system calls, filesystems, interrupts, and device management. "
        ) * 12
        copy_text = (
            "Cache mapping splits byte addresses into tag, set index, byte offset, "
            "cache lines, hits, misses, and replacement policy. "
        ) * 12

        year_topics = infer_topics([
            ExtractedDocument(
                path="Operating Systems (2024).pdf",
                title="Operating Systems (2024)",
                extension=".pdf",
                text=year_text,
                pages=[year_text],
            )
        ])
        copy_topics = infer_topics([
            ExtractedDocument(
                path="Cache Mapping (1).pptx",
                title="Cache Mapping (1)",
                extension=".pptx",
                text=copy_text,
                pages=[copy_text],
            )
        ])

        self.assertEqual("Operating Systems (2024)", year_topics[0].title)
        self.assertEqual("Cache Mapping", copy_topics[0].title)

    def test_inferred_topic_titles_remove_repository_course_prefixes_and_export_suffixes(self):
        fixtures = [
            (
                "mit-14-01-microeconomics-summaries",
                "Microeconomics",
                "Demand supply price market consumer utility marginal cost elasticity " * 16,
            ),
            (
                "mit-18-06-linear-algebra-zoomnotes",
                "Linear Algebra",
                "Matrix vector column row eigenvalue determinant basis orthogonal linear " * 16,
            ),
            (
                "mit-7-03-genetics-lecture-1",
                "Genetics",
                "Gene DNA mutation chromosome protein allele phenotype genotype inheritance " * 16,
            ),
            (
                "mit-24-00-ethics-handout",
                "Ethics",
                "Moral objectivity obligation reason value action ethical judgment philosophy " * 16,
            ),
            (
                "cmu-15-213-system-level-io-slides",
                "System Level Io",
                "File descriptor read write process stream input output buffer device kernel " * 16,
            ),
        ]
        docs = [
            ExtractedDocument(
                path=f"{raw_title}.pdf",
                title=raw_title,
                extension=".pdf",
                text=text,
                pages=[text],
            )
            for raw_title, _expected, text in fixtures
        ]

        topics = infer_topics(docs)

        self.assertEqual(
            {expected for _raw_title, expected, _text in fixtures},
            {topic.title for topic in topics},
        )

    def test_inferred_topic_keywords_drop_general_english_function_words_across_disciplines(self):
        text = (
            "The patient may may may know know our our first first concern, but airway breathing shock trauma "
            "assessment treatment emergency circulation fluid injury. "
        ) * 30
        doc = ExtractedDocument(
            path="basic-emergency-care.pdf",
            title="Basic Emergency Care",
            extension=".pdf",
            text=text,
            pages=[text],
        )

        topics = infer_topics([doc])

        self.assertIn("airway", topics[0].keywords)
        for noise in ("may", "know", "our", "first", "but"):
            self.assertNotIn(noise, topics[0].keywords)

    def test_inferred_topic_keywords_ignore_repeated_pdf_header_lines(self):
        text = "\n".join(
            f"[Page {page}]\n"
            "Example University\nDepartment of Medicine\nCopyright Notice\n"
            f"Case {page} uses airway assessment for breathing circulation shock trauma patient injury."
            for page in range(1, 21)
        )
        doc = ExtractedDocument(
            path="emergency-care.pdf",
            title="Emergency Care",
            extension=".pdf",
            text=text,
            pages=[text],
        )

        topics = infer_topics([doc])

        self.assertIn("airway", topics[0].keywords)
        for noise in ("example", "university", "department", "copyright"):
            self.assertNotIn(noise, topics[0].keywords)

    def test_inferred_topics_ignore_source_manifest_titles(self):
        text = (
            "Source provenance bibliography download URL license author publisher "
            "course material citation reference attribution archive. "
        ) * 20
        doc = ExtractedDocument(
            path="SOURCES.md",
            title="SOURCES",
            extension=".md",
            text=text,
            pages=[text],
        )

        topics = infer_topics([doc])

        self.assertEqual("General Course Review", topics[0].title)

    def test_course_screen_local_agent_initializer_does_not_read_persisted_api_key(self):
        class ForbiddenSecrets:
            def get_key(self):
                raise AssertionError("local agent course initialization must not read persisted API keys")

        settings = {
            "ai_provider": "local_agent",
            "ai_base_url": "local-agent://auto",
            "ai_model": "codex",
        }

        with tempfile.TemporaryDirectory() as tmpdir, \
             patch("ui.screens.course_screen.read_json", return_value=settings), \
             patch("core.secrets_manager.SecretsManager.instance", return_value=ForbiddenSecrets()):
            screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "courses")))
            initializer = screen._build_initializer()

        self.assertIsNotNone(initializer.summary_generator)
        self.assertIsNotNone(initializer.profile_generator)

    def test_generate_falls_back_to_local_summary_when_llm_returns_empty(self):
        client = FakeLLMClient("")
        client.last_error = "API request failed"
        generator = CourseSummaryGenerator(client)

        summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

        self.assertEqual("# Local Summary", summary)
        self.assertEqual("local", generator.summary_source)
        self.assertEqual("API request failed", generator.summary_warning)

    def test_initializer_can_use_injected_summary_generator(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager, summary_generator=FakeSummaryGenerator())
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(str(source), title="Systems", make_current=False)

            self.assertIn("# LLM Summary", project.summary_markdown)
            self.assertTrue(Path(project.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))

    def test_initializer_persists_injected_course_generation_profile(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(
                manager=manager,
                profile_generator=FakeProfileGenerator(),
            )
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(str(source), title="Systems", make_current=False)
            loaded = manager.get(project.course_id)

            self.assertEqual(24, loaded.generation_profile["question_count"])
            self.assertEqual("final_exam", loaded.generation_profile["template"])
            self.assertEqual("llm", loaded.generation_profile_source)
            self.assertEqual("", loaded.generation_profile_warning)

    def test_initializer_can_regenerate_existing_project_summary(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())
            project = initializer.initialize(str(source), title="Systems", make_current=False)
            original_id = project.course_id
            original_created_at = project.created_at

            initializer.summary_generator = FakeSummaryGenerator()
            initializer.profile_generator = FakeProfileGenerator()
            updated = initializer.regenerate_summary(project, make_current=False)

            self.assertEqual(original_id, updated.course_id)
            self.assertEqual(original_created_at, updated.created_at)
            self.assertIn("# LLM Summary", updated.summary_markdown)
            self.assertGreaterEqual(len(updated.topics), 1)
            self.assertGreaterEqual(len(updated.documents), 1)
            self.assertNotEqual(project.updated_at, updated.updated_at)
            self.assertTrue(Path(updated.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))
            self.assertEqual(24, updated.generation_profile["question_count"])
            self.assertEqual("llm", updated.generation_profile_source)

    def test_regenerate_summary_preserves_topic_id_when_inferred_title_changes(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            old_topic = CourseTopic(
                topic_id="cache_mapping",
                title="Cache Mapping",
                keywords=["cache", "tag", "set"],
                source_files=[str(source / "cache.pptx")],
            )
            project = CourseProject(
                course_id="course-topic-stability",
                title="Systems",
                source_folder=str(source),
                summary_markdown="# Old Summary",
                summary_path="",
                topics=[old_topic],
                documents=[],
                created_at="2026-06-18T00:00:00+00:00",
                updated_at="2026-06-18T00:00:00+00:00",
            )
            new_text = " ".join(
                ["cache", "mapping", "tag", "set", "offset", "hit", "miss", "line"] * 14
            )
            initializer.parser = FakeParser([
                ExtractedDocument(
                    path=str(source / "cache.pptx"),
                    title="Cache Address Mapping",
                    extension=".pptx",
                    text=new_text,
                    pages=[new_text],
                )
            ])

            updated = initializer.regenerate_summary(project, make_current=False)

            self.assertEqual(1, len(updated.topics))
            self.assertEqual("cache_mapping", updated.topics[0].topic_id)
            self.assertEqual("Cache Address Mapping", updated.topics[0].title)
            self.assertIn("Cache Mapping", updated.topics[0].aliases)
            self.assertIn("cache_address_mapping", updated.topics[0].aliases)
            self.assertIn("cache_mapping", updated.generation_profile["selected_topics"])
            self.assertIn("cache_mapping", updated.generation_profile["topic_weights"])

    def test_project_manager_repairs_stale_summary_path_on_save(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            stale_summary = Path(tmpdir) / "old-cwd" / "quiz_app" / "data" / "courses" / "course-stale_summary.md"
            project = CourseProject(
                course_id="course-stale",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Repaired Summary\n",
                summary_path=str(stale_summary),
                topics=self._topics(),
                documents=[],
                created_at="2026-06-18T00:00:00+00:00",
                updated_at="2026-06-18T00:00:00+00:00",
            )

            self.assertTrue(manager.save(project, make_current=False))

            repaired_summary = Path(manager.directory) / "course-stale_summary.md"
            self.assertEqual(repaired_summary, Path(project.summary_path))
            self.assertEqual("# Repaired Summary\n", repaired_summary.read_text(encoding="utf-8"))
            self.assertFalse(stale_summary.exists())

    def test_project_manager_never_uses_another_course_file_as_summary(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            victim = CourseProject(
                course_id="course-victim",
                title="Victim",
                source_folder="",
                summary_markdown="# Victim summary",
                summary_path="",
                topics=[],
                documents=[],
                created_at="2026-07-23T00:00:00+00:00",
                updated_at="2026-07-23T00:00:00+00:00",
            )
            self.assertTrue(manager.save(victim, make_current=False))
            victim_json = Path(manager.directory) / "course-victim.json"
            attacker = CourseProject(
                course_id="course-attacker",
                title="Attacker",
                source_folder="",
                summary_markdown="# Attacker summary",
                summary_path=str(victim_json),
                topics=[],
                documents=[],
                created_at="2026-07-23T00:00:00+00:00",
                updated_at="2026-07-23T00:00:00+00:00",
            )

            self.assertTrue(manager.save(attacker, make_current=False))

            self.assertEqual("Victim", manager.get("course-victim").title)
            self.assertEqual(
                Path(manager.directory) / "course-attacker_summary.md",
                Path(attacker.summary_path),
            )

    def test_project_manager_rolls_back_all_course_files_when_commit_fails(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            current_file = root / "current_course.json"
            manager = CourseProjectManager(
                str(root / "projects"),
                current_course_file=current_file,
            )
            project = CourseProject(
                course_id="course-transaction",
                title="Systems",
                source_folder=str(root / "source"),
                summary_markdown="# Original Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-07-13T00:00:00+00:00",
                updated_at="2026-07-13T00:00:00+00:00",
            )
            self.assertTrue(manager.save(project, make_current=False))
            current_file.write_text('{"course_id": "course-other"}', encoding="utf-8")

            project.summary_markdown = "# Replacement Summary\n"
            project.updated_at = "2026-07-13T01:00:00+00:00"

            real_replace = os.replace
            forward_replacements = 0

            def fail_current_pointer_commit(source, destination):
                nonlocal forward_replacements
                if ".course-save-" in str(source):
                    forward_replacements += 1
                    if forward_replacements == 3:
                        raise OSError("disk full")
                return real_replace(source, destination)

            with patch(
                "models.course_project.os.replace",
                side_effect=fail_current_pointer_commit,
            ):
                self.assertFalse(manager.save(project, make_current=True))

            stored = manager.get(project.course_id)
            self.assertEqual("# Original Summary\n", stored.summary_markdown)
            self.assertEqual("2026-07-13T00:00:00+00:00", stored.updated_at)
            self.assertEqual(
                "# Original Summary\n",
                Path(stored.summary_path).read_text(encoding="utf-8"),
            )
            self.assertEqual(
                {"course_id": "course-other"},
                json.loads(current_file.read_text(encoding="utf-8")),
            )

    def test_project_manager_prepare_failure_leaves_project_and_disk_unchanged(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-invalid",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[{"not_serializable": object()}],
                created_at="2026-07-13T00:00:00+00:00",
                updated_at="2026-07-13T00:00:00+00:00",
            )

            self.assertFalse(manager.save(project, make_current=False))

            self.assertEqual("", project.summary_path)
            self.assertFalse((Path(manager.directory) / "course-invalid.json").exists())
            self.assertFalse((Path(manager.directory) / "course-invalid_summary.md").exists())

    def test_project_manager_repairs_conflicting_course_artifact_paths(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            conflicting_path = Path(manager.directory) / "course-conflict.json"
            project = CourseProject(
                course_id="course-conflict",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path=str(conflicting_path),
                topics=self._topics(),
                documents=[],
                created_at="2026-07-13T00:00:00+00:00",
                updated_at="2026-07-13T00:00:00+00:00",
            )

            self.assertTrue(manager.save(project, make_current=False))

            self.assertEqual(
                str(Path(manager.directory) / "course-conflict_summary.md"),
                project.summary_path,
            )
            self.assertTrue(conflicting_path.exists())

    def test_project_manager_persists_summary_generation_status(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-status",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Local Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
                summary_source="local",
                summary_warning="API request failed",
            )

            self.assertTrue(manager.save(project, make_current=False))

            loaded = manager.get(project.course_id)
            self.assertEqual("local", loaded.summary_source)
            self.assertEqual("API request failed", loaded.summary_warning)

    def test_project_manager_persists_generation_profile_and_loads_legacy_defaults(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-profile",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
                generation_profile={"question_count": 20, "template": "quick_review"},
                generation_profile_source="llm",
                generation_profile_warning="",
            )

            self.assertTrue(manager.save(project, make_current=False))
            loaded = manager.get(project.course_id)

            self.assertEqual(20, loaded.generation_profile["question_count"])
            self.assertEqual("llm", loaded.generation_profile_source)
            legacy = CourseProject.from_dict({
                "course_id": "legacy",
                "title": "Legacy",
                "topics": [],
            })
            self.assertEqual({}, legacy.generation_profile)
            self.assertEqual("local", legacy.generation_profile_source)

    def test_course_screen_selects_first_project_and_enables_course_actions(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())
            initializer.initialize(str(source), title="Systems", make_current=False)

            screen = CourseScreen(manager)
            screen.refresh()

            self.assertEqual(0, screen.project_list.currentRow())
            self.assertTrue(screen.regenerate_action.isEnabled())
            self.assertTrue(screen.generate_questions_btn.isEnabled())

    def test_course_screen_reports_llm_fallback_after_initialization(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-fallback",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Local Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[{"path": "scan.pdf", "warnings": ["OCR unavailable"]}],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
                summary_source="local",
                summary_warning="API request failed",
            )
            screen = CourseScreen(manager)
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("en")

            with patch("ui.screens.course_screen.QMessageBox.information") as information:
                screen._on_init_done(project)

            message = information.call_args.args[2]
            self.assertIn("local summary", message.lower())
            self.assertIn("API request failed", message)
            self.assertIn("OCR unavailable", message)

    def test_course_screen_ignores_stale_init_worker_result(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)
            project = CourseProject(
                course_id="course-stale-init",
                title="Stale Init",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Stale\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )
            stale_worker = CourseScreen._InitWorker("", "", FakeSummaryGenerator())
            current_worker = CourseScreen._InitWorker("", "", FakeSummaryGenerator())
            screen._init_worker = current_worker
            stale_worker.finished.connect(screen._on_init_done)

            with patch("ui.screens.course_screen.QMessageBox.information") as information:
                stale_worker.finished.emit(project)

            information.assert_not_called()
            self.assertNotEqual("Stale Init", screen.summary_label.text())

    def test_course_screen_reports_llm_fallback_after_regeneration(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-fallback",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Local Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[{"path": "scan.pdf", "warnings": ["OCR unavailable"]}],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
                summary_source="local",
                summary_warning="API request failed",
            )
            screen = CourseScreen(manager)
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("en")

            with patch("ui.screens.course_screen.QMessageBox.information") as information:
                screen._on_regen_done(project)

            message = information.call_args.args[2]
            self.assertIn("local summary", message.lower())
            self.assertIn("API request failed", message)
            self.assertIn("OCR unavailable", message)

    def test_course_screen_ignores_stale_regen_worker_result(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)
            project = CourseProject(
                course_id="course-stale-regen",
                title="Stale Regen",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Stale Regen\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )
            stale_worker = CourseScreen._RegenWorker(project, FakeSummaryGenerator())
            current_worker = CourseScreen._RegenWorker(project, FakeSummaryGenerator())
            screen._regen_worker = current_worker
            stale_worker.finished.connect(screen._on_regen_done)

            with patch("ui.screens.course_screen.QMessageBox.information") as information:
                stale_worker.finished.emit((project, None))

            information.assert_not_called()
            self.assertNotEqual("Stale Regen", screen.summary_label.text())

    def test_course_screen_reports_topic_identity_repair_after_regeneration(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-topic-repair",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )
            report = TopicIdentityRepairReport(
                scanned=5,
                updated=2,
                unmatched=[
                    UnmatchedTopicQuestion("q-unknown", "Unknown Topic", "unmatched")
                ],
            )
            screen = CourseScreen(manager)
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("zh")

            with patch("ui.screens.course_screen.QMessageBox.information") as information:
                screen._on_regen_done((project, report))

            message = information.call_args.args[2]
            self.assertIn("已修复 2 道题目的知识点身份", message)
            self.assertIn("1 道题无法自动映射", message)

    def test_course_screen_reports_generation_profile_fallback(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)
            project = CourseProject(
                course_id="course-profile-fallback",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
                generation_profile_warning="invalid profile JSON",
            )

            message = screen._with_profile_warning("Course ready.", project)

            self.assertIn("invalid profile JSON", message)
            self.assertTrue("本地" in message or "local" in message.lower())

    def test_course_screen_limits_document_warning_details(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("en")
            project = CourseProject(
                course_id="course-warnings",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[{
                    "path": str(Path(tmpdir) / "scan.pdf"),
                    "warnings": ["warning one", "warning two", "warning three", "warning four"],
                }],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )

            message = screen._with_document_warnings("Course ready.", project)

            self.assertIn("scan.pdf", message)
            self.assertIn("warning one", message)
            self.assertIn("warning three", message)
            self.assertNotIn("warning four", message)
            self.assertIn("1 more", message)

    def test_course_screen_document_warnings_include_ocr_fix_options(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("en")
            project = CourseProject(
                course_id="course-ocr-warning",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[{
                    "path": str(Path(tmpdir) / "scan.pdf"),
                    "warnings": ["OCR fallback unavailable: tesseract executable not found"],
                }],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )

            message = screen._with_document_warnings("Course ready.", project)

            self.assertIn("OCR setup options", message)
            self.assertIn("winget install -e --id UB-Mannheim.TesseractOCR", message)
            self.assertIn("data/tessdata", message)

    def test_course_screen_leaves_message_unchanged_without_document_warnings(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            screen = CourseScreen(manager)
            project = CourseProject(
                course_id="course-clean",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[{"path": "notes.pdf", "warnings": []}],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )

            self.assertEqual(
                "Course ready.",
                screen._with_document_warnings("Course ready.", project),
            )

    def test_project_manager_delete_removes_project_summary_and_current_pointer(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            current_file = str(Path(tmpdir) / "current.json")
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(
                str(Path(tmpdir) / "projects"),
                current_course_file=current_file,
            )
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())

            kept = initializer.initialize(str(source), title="Keep", make_current=True)
            deleted = initializer.initialize(str(source), title="Delete", make_current=True)
            deleted_json = Path(manager.directory) / f"{deleted.course_id}.json"
            deleted_summary = Path(deleted.summary_path)

            self.assertTrue(manager.delete(deleted.course_id))

            self.assertFalse(deleted_json.exists())
            self.assertFalse(deleted_summary.exists())
            self.assertIsNone(manager.current())

            self.assertTrue(manager.set_current(kept.course_id))
            self.assertEqual(kept.course_id, manager.current().course_id)

    def test_course_screen_delete_uses_impact_snapshot_and_selected_policy(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            project = CourseProject(
                course_id="course-delete-policy",
                title="Systems",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Summary\n",
                summary_path="",
                topics=self._topics(),
                documents=[],
                created_at="2026-07-13T00:00:00+00:00",
                updated_at="2026-07-13T00:00:00+00:00",
            )
            self.assertTrue(manager.save(project, make_current=False))
            question_bank = Mock(name="question_bank")
            set_manager = Mock(name="set_manager")
            progress_manager = Mock(name="progress_manager")
            snapshot_manager = Mock(name="snapshot_manager")
            screen = CourseScreen(
                manager,
                question_bank=question_bank,
                set_manager=set_manager,
                progress_manager=progress_manager,
                snapshot_manager=snapshot_manager,
            )
            screen.project_list.setCurrentRow(0)
            impact = CourseAssetImpact(
                course_id=project.course_id,
                question_ids=("q1", "q2"),
                direct_set_ids=("set-a",),
                affected_set_ids=("set-a", "set-b"),
                progress_ids=("progress-a",),
                snapshot_ids=("snapshot-a",),
            )
            result = CourseRemovalResult(True, impact)

            with patch(
                "ui.screens.course_screen.analyze_course_asset_impact",
                return_value=impact,
            ) as analyze, patch.object(
                screen,
                "_choose_course_removal_mode",
                return_value=CourseRemovalMode.UNLINK_ASSETS,
            ), patch(
                "ui.screens.course_screen.remove_course_assets",
                return_value=result,
            ) as remove:
                screen._delete_selected_project()

            analyze.assert_called_once_with(
                project.course_id,
                question_bank,
                set_manager,
                progress_manager,
                snapshot_manager,
            )
            remove.assert_called_once_with(
                project.course_id,
                CourseRemovalMode.UNLINK_ASSETS,
                course_manager=manager,
                question_bank=question_bank,
                set_manager=set_manager,
                progress_manager=progress_manager,
                snapshot_manager=snapshot_manager,
            )

    def test_course_removal_impact_text_explains_counts_and_preserved_history(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            screen = CourseScreen(CourseProjectManager(str(Path(tmpdir) / "projects")))
            project = SimpleNamespace(title="Systems")
            impact = CourseAssetImpact(
                course_id="course-a",
                question_ids=("q1", "q2"),
                affected_set_ids=("set-a",),
                progress_ids=("progress-a", "progress-b", "progress-c"),
                snapshot_ids=("snapshot-a",),
            )
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("zh")

            text = screen._course_removal_impact_text(project, impact)

            self.assertIn("相关题目：2", text)
            self.assertIn("相关题集：1", text)
            self.assertIn("学习记录：3（始终保留）", text)
            self.assertIn("未完成草稿：1", text)

    def test_project_manager_current_returns_none_without_explicit_pointer(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            current_file = str(Path(tmpdir) / "current.json")
            manager = CourseProjectManager(
                str(Path(tmpdir) / "projects"),
                current_course_file=current_file,
            )
            project = CourseProject(
                course_id="course-safe",
                title="Safe Course",
                source_folder=str(Path(tmpdir) / "source"),
                summary_markdown="# Safe\n",
                summary_path="",
                topics=[],
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )

            self.assertTrue(manager.save(project, make_current=False))

            self.assertIsNone(manager.current())

    def test_project_manager_current_ignores_unsafe_course_pointer(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            root = Path(tmpdir)
            current_file = str(root / "current.json")
            manager = CourseProjectManager(
                str(root / "projects"),
                current_course_file=current_file,
            )
            project = CourseProject(
                course_id="course-safe",
                title="Safe Course",
                source_folder=str(root / "source"),
                summary_markdown="# Safe\n",
                summary_path="",
                topics=[],
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )
            outside = CourseProject(
                course_id="outside",
                title="Outside Course",
                source_folder=str(root / "outside-source"),
                summary_markdown="# Outside\n",
                summary_path=str(root / "outside-summary.md"),
                topics=[],
                documents=[],
                created_at="2026-06-23T00:00:00+00:00",
                updated_at="2026-06-23T00:00:00+00:00",
            )
            (root / "outside.json").write_text(
                json.dumps(outside.to_dict(), ensure_ascii=False),
                encoding="utf-8",
            )

            self.assertTrue(manager.save(project, make_current=False))
            Path(current_file).write_text('{"course_id": "../outside"}', encoding="utf-8")

            current = manager.current()

            self.assertIsNone(current)
            self.assertFalse(Path(current_file).exists())

    def test_course_screen_can_delete_selected_project(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            current_file = str(Path(tmpdir) / "current.json")
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(
                str(Path(tmpdir) / "projects"),
                current_course_file=current_file,
            )
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(str(source), title="Systems", make_current=True)
            screen = CourseScreen(manager)
            screen.refresh()
            screen.project_list.setCurrentRow(0)

            with patch.object(
                screen,
                "_choose_course_removal_mode",
                return_value=CourseRemovalMode.KEEP_ASSETS,
            ):
                screen.delete_action.trigger()

            self.assertIsNone(manager.get(project.course_id))
            self.assertEqual(0, screen.project_list.count())
            self.assertNotIn("Systems", screen.summary_label.text())

    def test_course_screen_guides_user_when_course_library_is_empty(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            language_manager = LanguageManager.instance()
            previous_language = language_manager.current
            self.addCleanup(language_manager.set_language, previous_language)
            language_manager.set_language("zh")

            screen = CourseScreen(manager)

            self.assertEqual(0, screen.project_list.count())
            self.assertFalse(screen.empty_state_label.isHidden())
            self.assertIn("还没有课程", screen.empty_state_label.text())
            self.assertIn("导入", screen.empty_state_label.text())
            self.assertFalse(screen.set_current_btn.isEnabled())
            self.assertFalse(screen.delete_action.isEnabled())

    def test_course_screen_can_rename_selected_project(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager)
            initializer.parser = FakeParser(self._docs())
            project = initializer.initialize(str(source), title="Systems", make_current=True)
            screen = CourseScreen(manager)
            screen.refresh()
            screen.project_list.setCurrentRow(0)

            with patch(
                "ui.screens.course_screen.QInputDialog.getText",
                return_value=("计算机系统期末", True),
            ):
                screen.rename_action.trigger()

            renamed = manager.get(project.course_id)
            self.assertEqual("计算机系统期末", renamed.title)
            self.assertIn("计算机系统期末", screen.project_list.item(0).text())
            self.assertIn("计算机系统期末", screen.summary_label.text())

    def test_course_screen_renders_summary_markdown_by_default(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "courses"))
            manager.save(CourseProject(
                course_id="course-rendered-summary",
                title="Systems",
                source_folder="",
                summary_markdown="# 课程总结\n\n## 核心概念\n\n**DMA** 减少 CPU 搬运。",
                summary_path="",
                topics=[],
                documents=[],
                created_at="2026-07-05T00:00:00+00:00",
                updated_at="2026-07-05T00:00:00+00:00",
            ))

            screen = CourseScreen(manager)

            self.assertIsInstance(screen.summary_preview, QTextBrowser)
            rendered_text = screen.summary_preview.toPlainText()
            self.assertIn("课程总结", rendered_text)
            self.assertIn("核心概念", rendered_text)
            self.assertNotIn("# 课程总结", rendered_text)
            self.assertNotIn("**DMA**", rendered_text)

    def test_course_screen_can_toggle_raw_markdown_summary(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            manager = CourseProjectManager(str(Path(tmpdir) / "courses"))
            manager.save(CourseProject(
                course_id="course-raw-summary",
                title="Systems",
                source_folder="",
                summary_markdown="# 课程总结\n\n**DMA** 减少 CPU 搬运。",
                summary_path="",
                topics=[],
                documents=[],
                created_at="2026-07-05T00:00:00+00:00",
                updated_at="2026-07-05T00:00:00+00:00",
            ))

            screen = CourseScreen(manager)
            screen.summary_mode_btn.click()

            self.assertIn("# 课程总结", screen.summary_preview.toPlainText())
            self.assertIn("**DMA**", screen.summary_preview.toPlainText())


if __name__ == "__main__":
    unittest.main()
