import tempfile
import unittest
from pathlib import Path

from ai.course_summarizer import CourseSummaryGenerator
from core.course_initializer import CourseInitializer
from core.document_parser import ExtractedDocument
from models.course_project import CourseProjectManager, CourseTopic


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class CourseSummaryGeneratorTests(unittest.TestCase):
    def _docs(self):
        return [
            ExtractedDocument(
                path="cache.pptx",
                title="Cache Mapping",
                extension=".pptx",
                text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                pages=["Cache line, byte offset, set, tag."],
            )
        ]

    def _topics(self):
        return [
            CourseTopic(
                topic_id="cache_mapping",
                title="Cache Mapping",
                keywords=["cache line", "tag", "set"],
                source_files=["cache.pptx"],
            )
        ]

    def test_generate_uses_llm_markdown_when_available(self):
        client = FakeLLMClient("# Semantic Summary\n\n## Cache Mapping\n- Use tag/set/offset.")
        generator = CourseSummaryGenerator(client)

        summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

        self.assertIn("# Semantic Summary", summary)
        self.assertIn("tag/set/offset", summary)
        self.assertIn("Cache line, byte offset", client.messages[1]["content"])

    def test_generate_falls_back_to_local_summary_when_llm_returns_empty(self):
        client = FakeLLMClient("")
        generator = CourseSummaryGenerator(client)

        summary = generator.generate("Systems", self._docs(), self._topics(), "# Local Summary")

        self.assertEqual("# Local Summary", summary)

    def test_initializer_can_use_injected_summary_generator(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "source"
            source.mkdir()
            manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
            initializer = CourseInitializer(manager=manager, summary_generator=FakeSummaryGenerator())
            initializer.parser = FakeParser(self._docs())

            project = initializer.initialize(str(source), title="Systems", make_current=False)

            self.assertIn("# LLM Summary", project.summary_markdown)
            self.assertTrue(Path(project.summary_path).read_text(encoding="utf-8").startswith("# LLM Summary"))


if __name__ == "__main__":
    unittest.main()
