import json
import tempfile
import unittest
from pathlib import Path
import os
from types import SimpleNamespace
from unittest.mock import Mock, patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication, QTextBrowser

from ai.course_summarizer import CourseSummaryGenerator
from ai.exam_plan import ExamGenerationPlan
from core.course_asset_lifecycle import (
    CourseAssetImpact,
    CourseRemovalMode,
    CourseRemovalResult,
)
from core.course_initializer import CourseInitializer, build_summary_markdown, infer_topics
from core.course_parse_checkpoint import CourseParseCheckpointStore
from core.document_parser import DocumentParser, ExtractedDocument
from core.background_task import BackgroundTaskCancelled, TaskControl, TaskProgress
from core.background_task_center import BackgroundTaskCenter, TaskStatus
from core.language_manager import LanguageManager
from core.topic_identity_migration import TopicIdentityRepairReport, UnmatchedTopicQuestion
from models.course_project import CourseProject, CourseProjectManager, CourseTopic
from ui.screens.course_screen import CourseScreen


_APP = QApplication.instance() or QApplication([])


class FakeLLMClient:
    def __init__(self, response):
        self.response = response
        self.messages = None
        self.last_error = ""

    def generate(self, messages, temperature=0.7, max_tokens=8000):
        self.messages = messages
        return self.response


class FakeParser:
    def __init__(self, docs):
        self.docs = docs

    def parse_folder(self, folder, task=None):
        return self.docs


class FakeSummaryGenerator:
    def generate(self, title, docs, topics, local_summary):
        return "# LLM Summary\n\n## 核心概念\n- Generated by fake LLM.\n"


class FakeProfileGenerator:
    profile_source = "llm"
    profile_warning = ""

    def generate(self, title, topics, summary_markdown):
        selected = tuple(topic.title.lower() for topic in topics)
        return ExamGenerationPlan(
            question_count=24,
            difficulty="hard",
            template="final_exam",
            selected_topics=selected,
            topic_weights={topic: 1 for topic in selected},
        )

class CourseProjectLifecycleTests(unittest.TestCase):
    def _docs(self):
            return [
                ExtractedDocument(
                    path="cache.pptx",
                    title="Cache Mapping",
                    extension=".pptx",
                    text="Cache line, byte offset, set, tag, and hit/miss calculation.",
                    pages=["Cache line, byte offset, set, tag."],
                )
            ]

    def _topics(self):
            return [
                CourseTopic(
                    topic_id="cache_mapping",
                    title="Cache Mapping",
                    keywords=["cache line", "tag", "set"],
                    source_files=["cache.pptx"],
                )
            ]

    def test_project_manager_repairs_stale_summary_path_on_save(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                stale_summary = Path(tmpdir) / "old-cwd" / "quiz_app" / "data" / "courses" / "course-stale_summary.md"
                project = CourseProject(
                    course_id="course-stale",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Repaired Summary\n",
                    summary_path=str(stale_summary),
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-18T00:00:00+00:00",
                    updated_at="2026-06-18T00:00:00+00:00",
                )

                self.assertTrue(manager.save(project, make_current=False))

                repaired_summary = Path(manager.directory) / "course-stale_summary.md"
                self.assertEqual(repaired_summary, Path(project.summary_path))
                self.assertEqual("# Repaired Summary\n", repaired_summary.read_text(encoding="utf-8"))
                self.assertFalse(stale_summary.exists())

    def test_project_manager_never_uses_another_course_file_as_summary(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                victim = CourseProject(
                    course_id="course-victim",
                    title="Victim",
                    source_folder="",
                    summary_markdown="# Victim summary",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-07-23T00:00:00+00:00",
                    updated_at="2026-07-23T00:00:00+00:00",
                )
                self.assertTrue(manager.save(victim, make_current=False))
                victim_json = Path(manager.directory) / "course-victim.json"
                attacker = CourseProject(
                    course_id="course-attacker",
                    title="Attacker",
                    source_folder="",
                    summary_markdown="# Attacker summary",
                    summary_path=str(victim_json),
                    topics=[],
                    documents=[],
                    created_at="2026-07-23T00:00:00+00:00",
                    updated_at="2026-07-23T00:00:00+00:00",
                )

                self.assertTrue(manager.save(attacker, make_current=False))

                self.assertEqual("Victim", manager.get("course-victim").title)
                self.assertEqual(
                    Path(manager.directory) / "course-attacker_summary.md",
                    Path(attacker.summary_path),
                )

    def test_project_manager_rolls_back_all_course_files_when_commit_fails(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                current_file = root / "current_course.json"
                manager = CourseProjectManager(
                    str(root / "projects"),
                    current_course_file=current_file,
                )
                project = CourseProject(
                    course_id="course-transaction",
                    title="Systems",
                    source_folder=str(root / "source"),
                    summary_markdown="# Original Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-07-13T00:00:00+00:00",
                    updated_at="2026-07-13T00:00:00+00:00",
                )
                self.assertTrue(manager.save(project, make_current=False))
                current_file.write_text('{"course_id": "course-other"}', encoding="utf-8")

                project.summary_markdown = "# Replacement Summary\n"
                project.updated_at = "2026-07-13T01:00:00+00:00"

                real_replace = os.replace
                forward_replacements = 0

                def fail_current_pointer_commit(source, destination):
                    nonlocal forward_replacements
                    if ".course-save-" in str(source):
                        forward_replacements += 1
                        if forward_replacements == 3:
                            raise OSError("disk full")
                    return real_replace(source, destination)

                with patch(
                    "models.course_project.os.replace",
                    side_effect=fail_current_pointer_commit,
                ):
                    self.assertFalse(manager.save(project, make_current=True))

                stored = manager.get(project.course_id)
                self.assertEqual("# Original Summary\n", stored.summary_markdown)
                self.assertEqual("2026-07-13T00:00:00+00:00", stored.updated_at)
                self.assertEqual(
                    "# Original Summary\n",
                    Path(stored.summary_path).read_text(encoding="utf-8"),
                )
                self.assertEqual(
                    {"course_id": "course-other"},
                    json.loads(current_file.read_text(encoding="utf-8")),
                )

    def test_project_manager_prepare_failure_leaves_project_and_disk_unchanged(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-invalid",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[{"not_serializable": object()}],
                    created_at="2026-07-13T00:00:00+00:00",
                    updated_at="2026-07-13T00:00:00+00:00",
                )

                self.assertFalse(manager.save(project, make_current=False))

                self.assertEqual("", project.summary_path)
                self.assertFalse((Path(manager.directory) / "course-invalid.json").exists())
                self.assertFalse((Path(manager.directory) / "course-invalid_summary.md").exists())

    def test_project_manager_repairs_conflicting_course_artifact_paths(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                conflicting_path = Path(manager.directory) / "course-conflict.json"
                project = CourseProject(
                    course_id="course-conflict",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path=str(conflicting_path),
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-07-13T00:00:00+00:00",
                    updated_at="2026-07-13T00:00:00+00:00",
                )

                self.assertTrue(manager.save(project, make_current=False))

                self.assertEqual(
                    str(Path(manager.directory) / "course-conflict_summary.md"),
                    project.summary_path,
                )
                self.assertTrue(conflicting_path.exists())

    def test_project_manager_persists_summary_generation_status(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-status",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Local Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                    summary_source="local",
                    summary_warning="API request failed",
                )

                self.assertTrue(manager.save(project, make_current=False))

                loaded = manager.get(project.course_id)
                self.assertEqual("local", loaded.summary_source)
                self.assertEqual("API request failed", loaded.summary_warning)

    def test_project_manager_persists_generation_profile_and_loads_legacy_defaults(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                manager = CourseProjectManager(str(Path(tmpdir) / "projects"))
                project = CourseProject(
                    course_id="course-profile",
                    title="Systems",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Summary\n",
                    summary_path="",
                    topics=self._topics(),
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                    generation_profile={"question_count": 20, "template": "quick_review"},
                    generation_profile_source="llm",
                    generation_profile_warning="",
                )

                self.assertTrue(manager.save(project, make_current=False))
                loaded = manager.get(project.course_id)

                self.assertEqual(20, loaded.generation_profile["question_count"])
                self.assertEqual("llm", loaded.generation_profile_source)
                legacy = CourseProject.from_dict({
                    "course_id": "legacy",
                    "title": "Legacy",
                    "topics": [],
                })
                self.assertEqual({}, legacy.generation_profile)
                self.assertEqual("local", legacy.generation_profile_source)

    def test_project_manager_delete_removes_project_summary_and_current_pointer(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                current_file = str(Path(tmpdir) / "current.json")
                source = Path(tmpdir) / "source"
                source.mkdir()
                manager = CourseProjectManager(
                    str(Path(tmpdir) / "projects"),
                    current_course_file=current_file,
                )
                initializer = CourseInitializer(manager=manager)
                initializer.parser = FakeParser(self._docs())

                kept = initializer.initialize(str(source), title="Keep", make_current=True)
                deleted = initializer.initialize(str(source), title="Delete", make_current=True)
                deleted_json = Path(manager.directory) / f"{deleted.course_id}.json"
                deleted_summary = Path(deleted.summary_path)

                self.assertTrue(manager.delete(deleted.course_id))

                self.assertFalse(deleted_json.exists())
                self.assertFalse(deleted_summary.exists())
                self.assertIsNone(manager.current())

                self.assertTrue(manager.set_current(kept.course_id))
                self.assertEqual(kept.course_id, manager.current().course_id)

    def test_project_manager_current_returns_none_without_explicit_pointer(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                current_file = str(Path(tmpdir) / "current.json")
                manager = CourseProjectManager(
                    str(Path(tmpdir) / "projects"),
                    current_course_file=current_file,
                )
                project = CourseProject(
                    course_id="course-safe",
                    title="Safe Course",
                    source_folder=str(Path(tmpdir) / "source"),
                    summary_markdown="# Safe\n",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )

                self.assertTrue(manager.save(project, make_current=False))

                self.assertIsNone(manager.current())

    def test_project_manager_current_ignores_unsafe_course_pointer(self):
            with tempfile.TemporaryDirectory() as tmpdir:
                root = Path(tmpdir)
                current_file = str(root / "current.json")
                manager = CourseProjectManager(
                    str(root / "projects"),
                    current_course_file=current_file,
                )
                project = CourseProject(
                    course_id="course-safe",
                    title="Safe Course",
                    source_folder=str(root / "source"),
                    summary_markdown="# Safe\n",
                    summary_path="",
                    topics=[],
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )
                outside = CourseProject(
                    course_id="outside",
                    title="Outside Course",
                    source_folder=str(root / "outside-source"),
                    summary_markdown="# Outside\n",
                    summary_path=str(root / "outside-summary.md"),
                    topics=[],
                    documents=[],
                    created_at="2026-06-23T00:00:00+00:00",
                    updated_at="2026-06-23T00:00:00+00:00",
                )
                (root / "outside.json").write_text(
                    json.dumps(outside.to_dict(), ensure_ascii=False),
                    encoding="utf-8",
                )

                self.assertTrue(manager.save(project, make_current=False))
                Path(current_file).write_text('{"course_id": "../outside"}', encoding="utf-8")

                current = manager.current()

                self.assertIsNone(current)
                self.assertFalse(Path(current_file).exists())
